### ISSUE TITLE
Two Quick Questions about OPcache and php.ini Configuration

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#101]
Hi Michael & Andreas,

I have two quick questions...

Is there any way to control the OPcache settings (like the 300 seconds) for all of the instances?

and

Is there any way to control the php.ini settings for all of the instances?

The instances are automatically generated (and deleted), and I do not know where they get their configurations from. I'm assuming they must be using an AMI from somewhere. But there must be a way to customize these settings so that they exist on all the instances...

~ Michael

**Comment by kbcaleb** [comment]
You can jump from your bastion server to execute some sed to fix things.
```shell
sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 20M/' /etc/php.ini
sed -i 's/post_max_size = 8M/post_max_size = 20M/' /etc/php.ini
service httpd restart
```

**Comment by ILLUMINICE** [comment]
Hi Caleb,

That was kind of you to reply...

If I did what you suggested here wouldn't the changes simply be reset when the auto-scaling policy creates new instances?

This is what I'm really trying to figure out right now. I know I can change these settings directly, but it would only be on that one instance. I need my changes to be permanent and applied to all instances, present and future.

If you know how to do this, that would be awesome!

~ Michael

**Comment by michaelwittig** [comment]
https://github.com/widdix/aws-cf-templates/blob/master/wordpress/wordpress-ha-aurora.yaml#L584

**Comment by gurumark** [comment]
@ILLUMINICE Did you find a solution to this issue to keep it permanent? 

I have no idea what line 584 means on @michaelwittig post and how it is related to this issue.

**Comment by ILLUMINICE** [comment]
@gurumark If memory serves me Michael Wittig's reference was originally correct, and the template has simply been modified since then (so the line numbers have changed)... ;)

The solution that was proposed above by @kbcaleb was the correct solution and it is indeed permanent. At the time I didn't realize that this was part of the launch configuration, and that whenever an instance is created it is using these settings.

The sed command is a find/replace within a string. It's pretty cool actually. It is able to find a specific portion of a string and simply replace it. So in this case we simply tell it to look for the OPcache or php.ini settings and to replace them as we specify. This occurs at the time the instance is launched, and so it is effectively permanent (at least until you change your template again).

Here are my settings for php.ini and OPcache using sed:

```
          files:
            '/root/php.sh':
              content: !Sub |
                #!/bin/bash -ex
                sed -i 's/;opcache.revalidate_freq=2/opcache.revalidate_freq=300/g' /etc/php-7.0.d/10-opcache.ini
                sed -i 's/max_execution_time = 30/max_execution_time = 300/' /etc/php.ini
                sed -i 's/max_input_time = 60/max_input_time = 300/' /etc/php.ini
                sed -i 's/; max_input_vars = 1000/max_input_vars = 10000/' /etc/php.ini
                sed -i 's/memory_limit = 128M/memory_limit = 512M/' /etc/php.ini
                sed -i 's/post_max_size = 8M/post_max_size = 200M/' /etc/php.ini
                sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 200M/' /etc/php.ini
                sed -i 's/max_file_uploads = 20/max_file_uploads = 200/' /etc/php.ini
```
So simply look for this section in your template and modify it to your desired settings. I'm assuming you're using one of the WordPress templates, which have this section in place already.

Hope this helps!

**Comment by gurumark** [comment]
@ILLUMINICE Thanks for your response. Yes, it is very helpful indeed.
We're planning to use these templates in our production environment. Reading your posts here makes me a little hesitant though. It seems there are things which are totally out of your control and dependent on cloud formation team's development timeline. 
So what your experience has been so far in terms of running WordPress in production using these templates? 
Thanks again for your help!

**Comment by ILLUMINICE** [comment]
@gurumark You've certainly asked me a loaded question here. I'll try to answer as simply as possible.

I have two environments currently setup using these templates, one for production and one for development. My team is developing a very large social media platform, and we're still in a pre-launch status. So I can't speak from a true production environment experience just yet.

With that said, I chose to go with AWS because it is the oldest and most established of all cloud computing platforms. For a website such as ours that will ultimately grow very large (or so we hope), using a service such as AWS was the only viable solution. When I first joined AWS (just over a year ago now) I was extremely overwhelmed by the new environment. My previous experience was all in independent non-cloud servers.

The reason I chose CloudFormation and this particular set of templates was because it greatly simplified the deployment of a complex infrastructure stack. Without a template such as this I would have had to configure everything manually and separately. One of the greatest advantages of using CF is that it ties together your entire stack so that resources are organized and can be versioned. It allows you to easily have multiple environments within the same account and not confuse what does with what. On a more fundamental note, I simply didn't have the knowledge at the time to set this all up without CF (though now I do...).

I've been working with these templates for a year now, and I have nothing but good things to say about them. The Widdix brothers are constantly improving them, and frankly there are no better templates out there for WordPress and AWS (believe me, I looked). Over this past year I have created my own version of these templates, differentiating them for my particular needs. I have the original templates and my edited versions in a separate repo. I watch the updates made to the originals and merge those changes into my versions regularly.

I don't know your level of AWS expertise, but I can tell you that it does take time to learn this all. I am a great deal more comfortable now working with CF and AWS then I was 6 months ago, and especially one year ago. I have done my best to learn CF and look up what I need to know. The Widdix brothers helped me a little early on, but they simply don't have the time for lengthy questions and answers. Most of what I have accomplished I have by teaching myself.

If you're looking to use WordPress and want to create a very stable, scale-able and available platform, then this is definitely the way to do it. AWS has all the tools for this, and CloudFormation is the automation system for deployment. But with all these systems and tools comes a great degree of knowledge to use them. If you are new to all of this, it can be very intimidating at first. But I assure you this can be learned with time and patience.

Regarding your comment about CF and the lack of control with updates; to my knowledge you can control just about anything in AWS via CF. It's a very capable deployment tool. The json format used in these templates is also pretty easy to learn. You can look up just about anything you want to do in the AWS documentation.

Lastly, I can tell you that there are a lot of configuration details of having WP in AWS that go beyond these templates. WP isn't exactly cloud compatible at first. For example, it's a very bad idea to run any WP updates of any kind in this environment. I deactivated that ability with a wp-config constant, and only update WP from my local environment. I then deploy all changes using Beanstalk (https://beanstalkapp.com/).

There's a lot to know to do this all! ;)

But the shortest answer to your question is that CloudFormation is pretty amazing, and these templates are phenomenal. If you do choose to use these and would like further advice please feel free to contact me directly at Michael@Eruditely.com.
