### ISSUE TITLE
Migrate to New Relic Infrastructure

### ISSUE THREAD

**Issue by rtizzy** [widdix/aws-cf-templates#103]
The existing NR monitoring is being deprecated and replaced by NR Infrastructure. 

NR Infrastructure does not appear to have a free tier, though I may be incorrect. 

See the following thread for more details. 

https://github.com/widdix/aws-cf-templates/issues/95

**Comment by kbcaleb** [comment]
#118 

Whipped this up for this feature if you want to pull it in for a new release.
