### ISSUE TITLE
Installing PHP GD Library

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#109]
Hi Michael,

Sorry to bother you with this, but I figured you could provide a quick answer.

I need to install the GD library for PHP via the CloudFormation template, so it's present on all the instances.

I'm not exactly sure how to do this and where to place it in the template. Can you help?

~ Michael

**Comment by ILLUMINICE** [comment]
It looks like I figured this one out on my own...

I've bolded what I did below. Please let me know if I missed any other considerations.

.....

config:
          packages:
            yum:
              php70: []
              **php70-gd: []**
              php70-opcache: []
              php70-mysqlnd: []
              mysql56: []
              httpd24: []

**Comment by michaelwittig** [comment]
Hi Michael,
the solution you provide looks fine.
