### ISSUE TITLE
Travis Validation Failures

### ISSUE THREAD

**Issue by kbcaleb** [widdix/aws-cf-templates#113]
Travis-CI is marking builds as good when they have failed the validation-template command. This is being caused by using the find -exec.

The [POSIX standard](http://pubs.opengroup.org/onlinepubs/009695399/utilities/find.html) specifies that the return status of the find is 0 unless an error occurred while traversing the directories; the return status of executed commands doesn't enter into it.

The topper is that the AWS cli only returns exit 1 for S3 calls and uses other codes for results.
http://docs.aws.amazon.com/cli/latest/topic/return-codes.html

I used this janky bit of code to get each one to parse individually and exit properly.
```yaml
script:
- 'yamllint . && for i in `find . -type f -name ''*.y?ml''`;do set -e && aws cloudformation validate-template --template-body file://./$i ;done'
```
However, this creates a bug with max file size of the [jenkins-ha-agents template](https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha-agents.yaml). This bug does not occur if you parse it from S3 though as usual.

S3 Parse:
```shell
aws cloudformation validate-template --template-url https://s3.amazonaws.com/immdevops/jenkins2-ha-agents.yaml
```
File Parse:
```shell
aws cloudformation validate-template --template-body file://./jenkins/jenkins2-ha-agents.yaml
An error occurred (ValidationError) when calling the ValidateTemplate operation: 1 validation error detected: Value '---' at 'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200
```

**Comment by michaelwittig** [comment]
good catch... I'm working on it
