### ISSUE TITLE
Jenkins: add configurable root device volume size in launch configuration

### ISSUE THREAD

**Issue by cuipengfei** [widdix/aws-cf-templates#115]
Thanks for making these templates publicly available!

For the jenkins2-ha.yaml, in its AWS::AutoScaling::LaunchConfiguration section, there is 
 no specification for a root device size.

After running jenkins2-ha.yaml, I get a ec2 machine like this:
```
Filesystem                                 Size  Used Avail Use% Mounted on
devtmpfs                                   2.0G   60K  2.0G   1% /dev
tmpfs                                      2.0G     0  2.0G   0% /dev/shm
/dev/xvda1                                 7.8G  4.6G  3.2G  60% /
fs-d909d810.efs.eu-west-1.amazonaws.com:/  8.0E  998M  8.0E   1% /var/lib/jenkins
```

/var/lib/jenkins certainly will have enough space for most cases.

But the default root device size could easily be used up.

Could a configurable root device volume size be added in launch configuration?

**Comment by michaelwittig** [comment]
It could but do you have taken into account that `/var/lib/jenkins` resides on an EFS volume. It will not consume your EBS root volume's space.

**Comment by cuipengfei** [comment]
Yes, I was aware of that.

We are running something that's heavily dependent on docker, and we are using a bunch of different images.

Under my jenkins instance's /var/lib/
 
```
    4.4GiB [##########] /docker
    1.0GiB [##        ] /jenkins
   19.7MiB [          ] /rpm
  932.0KiB [          ] /yum
```

Jenkins itself is not using too much space, docker is using more and it's likely to increase.

**Comment by michaelwittig** [comment]
I agree. This is now a feature request :)
