### ISSUE TITLE
EFS Burst Credit Balance and Permitted Throughput Should Be Monitored and Alerted On

### ISSUE THREAD

**Issue by elricsfate** [widdix/aws-cf-templates#116]
The best way to implement this is going to be a subject for debate but what is certain is this is absolutely something that should be done, or at least a footnote placed regarding EFS performance. 

Problem: 

Due to how EFS throughput scales, additional storage usage means additional throughput. 

In cases where there is low usage of storage but high traffic, this means that after initial credits are utilized that the performance slams to an absolute crawl. 

An unfortunate outcome is that after you've reached this point it's almost impossible to add additional storage without waiting for burst credits to regenerate since the only way to accrue credits faster is to use more storage (Which is impossible due to the crippled throughput)

Solution:

These metrics should be reported and alerted on in a fashion that will allow users to mitigate potential downtime by using additional storage as needed.

**Comment by michaelwittig** [comment]
One question: WordPress template?:)

We have alerts in the Jenkins template: https://github.com/widdix/aws-cf-templates/blob/master/jenkins/jenkins2-ha.yaml#L171

I will have a deeper look next week...

**Comment by michaelwittig** [comment]
And yes: I agree that there should be alerts for the metrics you mentioned!

**Comment by elricsfate** [comment]
haha, always do this to you guys. Yep, this is regarding the Wordpress templates @michaelwittig

**Comment by michaelwittig** [comment]
we alert on BurstCreditBalance for all templates. 

I don't think that it makes sense to monitor PermittedThroughput because this really depends on the amount of storage you use in EFS so I can not really set meaningful thresholds for this.

Feel free to reopen the issue if this does not satisfy your requirements.
