### ISSUE TITLE
Monitor RDS instances

### ISSUE THREAD

**Issue by elricsfate** [widdix/aws-cf-templates#117]
Equivalent monitoring for RDS instances. See the following for additional information

https://github.com/widdix/aws-cf-templates/issues/116

**Comment by michaelwittig** [comment]
This applies to the WordPress template that uses RDS.

Metrics to monitor:

* BurstBalance
* CPUUtilization
* CPUCreditBalance
* DiskQueueDepth
* FreeStorageSpace

http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rds-metricscollected.html
