### ISSUE TITLE
Access Aurora Database

### ISSUE THREAD

**Issue by chiragchhita** [widdix/aws-cf-templates#119]
Hi there,
I have created a wordpress setup using your cloud formation templates which are great!   I have attempted to connect to the database but cannot seem to do so.  I used the template using Aurora DB, and have previously been able to connect to the Aurora DB (in a different setup) using an SSH Tunnel via Putty.  this worked great, but with this setup, i appear to be having issues.

I tried to create an SSH tunnel via the SSH bastion instance, so i could use a desktop database tool to access the DB via localhost, but this doesnt seem to work.

Did I miss a step in the process?

Thanks for the template and for the help

**Comment by michaelwittig** [comment]
You have to modify the security group of the aurora database to allow connections from the bastion host.

We could enable this by default if the bastion host approach is used. What do you think?

**Comment by chiragchhita** [comment]
that works great! I was simply missing the security group setting from the bastion.  i can now access my database.  
Thanks again!
