### ISSUE TITLE
Monitor Nat Gateway

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-cf-templates#120]
https://aws.amazon.com/de/about-aws/whats-new/2017/09/amazon-vpc-nat-gateways-now-support-amazon-cloudwatch-monitoring-and-resource-tagging/

**Comment by justinHensley** [comment]
@michaelwittig would you take a PR for this? or have you already started on it.

**Comment by michaelwittig** [comment]
I would be happy to merge your PR. I have not yet started working on it.
