### ISSUE TITLE
t2.micro insufficient for wordpress template

### ISSUE THREAD

**Issue by durkode** [widdix/aws-cf-templates#132]
TemplateID: wordpress/wordpress-ha
Region: ap-southeast-2

I previously attempted to launch the wordpress-ha template in ap-southeast-2 running on t2.micro, which is the default for the template. This caused the creation to fail with the error: 

`Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement`

Removing auto rollback I went to diagnose the issue, and it seemed that everything worked successfully, and wordpress seemed to work fine for everything created up until that point. Logs all looked perfectly normal. I suspect that it took too long to spin up on a t2.micro, hence failing a health check and failing the stack creation. Running again using t2.medium was successful.

A solution is to either changing the default instance type to something beefier than t2.micro (and document this limitation), or perhaps increasing the health check grace period?

**Comment by michaelwittig** [comment]
Hi @durkode the download time of WordPress itself can also be an issue.

To debug this further, could you retry to create a stack with t2.micro to confirm that it is always not working / sometimes working. 

We spin up the WordPress stack weekly (in us-east-1) using t2.micro and we have no issued with this so far. But maybe this is different in ap-southeast-2.

**Comment by durkode** [comment]
Thanks for the reply @michaelwittig and apologies for the very delayed response. Today I ran through setting up the stack in both us-east-1 and ap-southeast-2 and had no problems doing so in either region on a t2.micro instance. I'm putting this one down to an intermittent issue in ap-southeast-2 when I originally ran into the problem.
