### ISSUE TITLE
Limitation of 2 AZs

### ISSUE THREAD

**Issue by markusbecker** [widdix/aws-cf-templates#141]
Hey Guys,

thank you very much for the cool and intuitive template for the jenkins setup (HA). Is there a reasoning behind limiting it to 2 AZs? Wouldnt it be possible to create a third mount target and span the ASG to 3 AZs? I can do this by myself, but was wondering if you know any reason not to do it. 

Thanks in advance. 

best,
Markus

**Comment by michaelwittig** [comment]
Hi @markusbecker 

The reason behind this: The information how many AZs the VPC has is in the ParentVPCStack. Unfortunately, CloudFormation does not support the ImportValue function in Conditions so we can not dynamically add a MountPoint Depending on AZs.

If there are any ideas how we overcome this limitation?
