### ISSUE TITLE
Upgrading Jenkins template - results in rollback because of AgentASG

### ISSUE THREAD

**Issue by htplbc** [widdix/aws-cf-templates#147]
TemplateID: jenkins/jenkins2-ha-agents)
Region: us-east-2

Upgrading the AMIs results in multiple 'Jenkins agents groups' to spin up per master. The old master will have a set of agents, In my case 2. The new master will then spin up additional agents. After the Master updates are done the AgentASG update thinks that there are about double the amount of agents. This results in a "Unable to satisfy 100% MinSuccessfulInstancesPercent requirement" failure.

**Comment by htplbc** [comment]
Here is the stack update events exported
[events.zip](https://github.com/widdix/aws-cf-templates/files/1644747/events.zip)

**Comment by sandrokeil** [comment]
I can confirm it. I update Jenkins only if no agents are running. In my case, agents are running only from 9 am - 18 pm. If your agents are running all the time, I guess you have to deploy a new Cloudformation template where agents are disabled, update Jenkins, and then redeploy with agents.

**Comment by michaelwittig** [comment]
yes, I believe you have to first stop all agents. to do so

1. update the stack, set agent min/max/desired to 0
2. update stack with the new template version
3. update the stack with the old agent min/max/desired values

sorry for this...

**Comment by michaelwittig** [comment]
@htplbc is the update working now for you?

**Comment by htplbc** [comment]
@michaelwittig yes it works. Thanks
