### ISSUE TITLE
ECS ScaleDown policy overrides desired capacity of instances and tasks

### ISSUE THREAD

**Issue by sandrokeil** [widdix/aws-cf-templates#149]
Thank you very much for this awesome templates. Maybe I encountered an error.

TemplateID: ecs/cluster
Region: eu-central-1

My goal is to have an EC2 instance in availibility zone A and B and that each service has a disired capacity of 2. So each service is placed in zone A and B to have failover. It looks like the scale down policy overrides this.

AutoScalingGroup Log of ECS Cluster
```
Description:DescriptionLaunching a new EC2 instance: i-123
--
Cause:
At 2018-02-14T09:21:34Z a user request update of AutoScalingGroup constraints to min: 1, max: 3, desired: 2 changing the desired capacity from 1 to 2. 
At 2018-02-14T09:21:45Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.
```

```
Description:DescriptionTerminating EC2 instance: i-123
--
Cause:
At 2018-02-14T09:27:44Z a monitor alarm ContainerInstancesExcessAlarm in state ALARM triggered policy ScaleDownPolicy changing the desired capacity from 2 to 1. 
At 2018-02-14T09:28:04Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 2 to 1. 
At 2018-02-14T09:28:04Z instance i-123 was selected for termination.
```

ECS service event log
```
Message: Successfully set desired count to 1. Change successfully fulfilled by ecs. 
Cause: monitor alarm CPUUtilizationLowAlarm in state ALARM triggered scale-down
```

**Comment by michaelwittig** [comment]
Hi @sandrokeil Maybe I get your question wrong... If you want to have at leats two EC2 Instances and ECS tasks, you have to set min size to 2 for the EC2 cluster and the ECS service.

**Comment by sandrokeil** [comment]
You are right. I misinterpreted [desired count](https://stackoverflow.com/a/39406170). Thank you again Michael.
