### ISSUE TITLE
service-link role for Elasticsearch

### ISSUE THREAD

**Issue by bitmatix** [widdix/aws-cf-templates#157]
TemplateID: state/elasticsearch.yaml
Region: (e.g. `eu-central-1`)

I'm trying to setup Elasticsearch based on your template, but I do get an error:

AWS::Elasticsearch::Domain CREATE_FAILED Before you can proceed, you must enable a service-linked role to give Amazon ES permissions to access your VPC.

Do I have to create the service-linked role by myself before I can rollout the stack?

**Comment by michaelwittig** [comment]
from the documentation http://templates.cloudonaut.io/en/stable/state/#elasticsearch:

step 1: `aws --region eu-central-1 iam create-service-linked-role --aws-service-name es.amazonaws.com`

Unfortunately, it's not possible to create a service linked role in CloudFormation yet.
