### ISSUE TITLE
TIBCO-EMS-BastionStack

### ISSUE THREAD

**Issue by s0l0h** [widdix/aws-cf-templates#165]
Hello guys.

I'm new to AWS i followed a quickstart template to create TIBCO ems but i keep getting this issue there is no logs in cloudwatch the only log from console events as shown below. pls help guys

16:21:59 UTC+0100 | CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | BastionAutoScalingGroup | Received 0 SUCCESS signal(s) out of 1.  Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

**Comment by michaelwittig** [comment]
what is TIBCO-EMS-BastionStack?
Is it based on https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-ssh-bastion.yaml?
Any modifications?
Which AWS region?

**Comment by s0l0h** [comment]
this is the link used 
https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/new?stackName=TIBCO-EMS&templateURL=https://s3.amazonaws.com/quickstart-reference/tibco/ems/latest/templates/tibco-ems-master.template

**Comment by michaelwittig** [comment]
sorry, but this is not at all related to this repository. you may find more information here: https://aws.amazon.com/de/quickstart/architecture/tibco-ems/

**Comment by s0l0h** [comment]
it's the same i'm using but it's not working it's stopped on creating bastion auto scaling group
