### ISSUE TITLE
cluster.yml : member must have length less than or equal to 51200

### ISSUE THREAD

**Issue by gaboesquivel** [widdix/aws-cf-templates#169]
TemplateID: ecs/cluster
Region: us-east-1

aws cloudformation create-stack --stack-name one-cluster --parameters file:///$PWD/environments/one/infrastructure/cluster.json --template-body file:///$PWD/infrastructure/cluster.yml

'templateBody' failed to satisfy constraint: Member must have length less than or equal to 51200

**Comment by michaelwittig** [comment]
hi @gaboesquivel you run into a CloudFormation limitation. Templates larger than 51200 bytes must first be uploaded to s3, and then you specify them via `--template-file`

**Comment by Tarvinder91** [comment]
Adding my 2 cents for people following the issue, you shall store your template on s3 first and use the following option in the aws cmd line as a workaround for large templates -

--template-url https://s3-<region>.amazonaws.com/...../yourtemplate.json

url should be https link of the template.
