### ISSUE TITLE
Trap for the unwary – KMS key deletion in RDS postgres template

### ISSUE THREAD

**Issue by btisdall** [widdix/aws-cf-templates#171]
Since this template (and possibly others) manages its own KMS key less experienced users or the uncareful may find themselves unable to access encrypted snapshots once the source stack has been deleted. Some thoughts:

1. Just provide a prominent health warning (not very keen on this).
2. Set a deletion policy of `Retain` on the key by default, flip-able with a parameter.
3. Allow the KMS key ID to optionally be provided via a parent stack rather than managed in-template.

**Comment by michaelwittig** [comment]
Hi @btisdall 

1. I agree, the warning is not the best solution
2. Last time I tried this it was not possible to `!Ref` a value in the DeletionPolicy. So we could only always `Reatain`KMS keys
3. This would be my preferred option. Only concern is that the key policy must be more open because I don't know if the key is used for s3, rds, or es, ... but this could also be an option... hm

Any thoughts?

**Comment by btisdall** [comment]
Ah yes... `Template format error: Every DeletionPolicy member must be a string.`.

This is one area where tf scores better for composability. I think the best you could do in cfn is provide a companion kms key template (much as you do with `client-sg`), though if the fallback is for the db template to manage the key this still leaves the problem for less experienced users who are the ones most likely not to use a parent stack, so there's still a case for hard coding `Retain`...

**Comment by btisdall** [comment]
I think the best compromise is to make the in-template key `Retain`ed with a warning that if it is not manually cleaned up after stack deletion ongoing charges will apply. Better that that warning is ignored and people are out a few bucks than a key gets deleted by mistake. Meanwhile introduce a parent key stack with the usual conditional logic.

**Comment by michaelwittig** [comment]
v9 will be released soon which fixes this issue..
