### ISSUE TITLE
[ECS] Hosted Zone Stack need to be in the same region

### ISSUE THREAD

**Issue by jrbenito** [widdix/aws-cf-templates#177]
hi,

In the service templates if Hosted Zone Stack is used it need to exist in the same aws region. This could be a issue if "someone.io" is registered by zone stack in AWS region us-east-1 but for some reason, someone need ECS clusters in sa-east-1 and us-west-1 and, for instance, a service in us-west-1 needs to register a DNS as "service-for-west.someone.com", similarly, a task in ecs cluser sa-east-1 would regiser "another-service-in-brazil.someone.com". 

I don't know if it is a AWS limitation in regard getting cross zone paramenter but maybe this could be solved using ARN?

Thanks.

**Comment by michaelwittig** [comment]
Hi @jrbenito 

Route53 is global but CloudFormation (we rely on the exports here) are regional.

You can try the following:
1. in sa-east-1, create a stack based on https://github.com/widdix/aws-cf-templates/blob/master/vpc/zone-legacy.yaml using the values from the zone stack in us-east-1
2. create the ecs cluster using the zone-legacy stack name as the `ParentZoneStack`

Let me know if this works.

**Comment by jrbenito** [comment]
Hi @michaelwittig 

I think I lost the part which clearly states it. Sorry!

> If you have an existing Route53 Hosted Zone you can wrap it into our required form using a legacy zone wrapper

It worked, thanks a lot.

**Comment by michaelwittig** [comment]
Your use case is quiet special and interesting. I'm glad that it was possible to get your ECS cluster stack up and running.
