### ISSUE TITLE
Problem when launching EC2 instances using Wordpress template...

### ISSUE THREAD

**Issue by wysow** [widdix/aws-cf-templates#18]
Hello,

First of all thanks for this complete cloudformation template!

That's the first time I try Cloudformation for what I call "an advanced stack" (for me at least).

I have setup the `vpc-2azs.json` template before this one and I'm using it's output during configuration step.

I've made some debug and I'm pretty sure that the guilty lines are:

```
"curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \n",
"php wp-cli.phar core install --url=\"", {"Fn::GetAtt": ["LoadBalancer", "DNSName"]}, "\" --title=\"", {"Ref": "BlogTitle"}, "\" --admin_user=\"", {"Ref": "BlogAdminUsername"}, "\" --admin_password=\"", {"Ref": "BlogAdminPassword"}, "\" --admin_email=\"", {"Ref": "BlogAdminEMail"}, "\" --skip-email \n",
"php wp-cli.phar plugin install --activate amazon-web-services \n",
"php wp-cli.phar plugin install --activate amazon-s3-and-cloudfront \n"
```

But I can't manage to get an error output from EC2 instances before they terminate... 

Can someone help me on this?

**Comment by wysow** [comment]
Humm... Just tried to reset everything to default template and seems that using newer AMI does break the whole thing... Sounds possible for you?

**Comment by andreaswittig** [comment]
Hi,

that’s possible. Will check and fix that.

Andreas

**Comment by andreaswittig** [comment]
Updated the templates with the latest AMI. Everything still working as expected. Could you provide some more information about your issues, please?

**Comment by wysow** [comment]
Hum... I did it with another way but maybe I was not using the right AMIs... If I find the time to test it with your updated version I'll keep you posted, closing for now thanks for taking time to handle this...
