### ISSUE TITLE
Why is mariadb installed for vpc-ssh-bastion?

### ISSUE THREAD

**Issue by sandrokeil** [widdix/aws-cf-templates#184]
TemplateID: vpc/vpc-ssh-bastion
Region: `eu-central-1`

Why is MariaDB installed [here](https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-ssh-bastion.yaml#L399)?

**Comment by michaelwittig** [comment]
the bastion host has access to the database stacks. the idea was that you have the tools installed to make a connection to mysql like databases.

**Comment by sandrokeil** [comment]
Alright, so I will remove it for my stack. Thanks Michael.
