### ISSUE TITLE
Issues to deploy WordPress (error 502)

### ISSUE THREAD

**Issue by mr3k** [widdix/aws-cf-templates#190]
TemplateID: wordpress/wordpress-ha-aurora
Region: eu-west-1

Hello,

I have tried to deploy your CloudFormation template for WordPress. What I did was:
1. Install Template for "VPC with private and public subnets in three Availability Zones"
2. Followed the guide for "WordPress: fault tolerant and scalable (Aurora)"

However, when I try open the website I get Error 502: "CloudFront wasn't able to connect to the origin.".

Can you let me know what dependencies is really needed. I see "vpc/vpc-*azs.yaml" and also the DNS zones seems needed (input needed in the template) even though it is not listed. Is there anything more? NAT Gateway?

**Comment by michaelwittig** [comment]
Hi @mr3k 

can you share the parameters you used for the wordpress stack, e.g. using `aws -cloudformation describe-stacks --stack-name NAME_OF_YOUR_STACK --query 'Stacks[0].Parameters[]'`

**Comment by mr3k** [comment]
Please see attached image. 

I have both used the legacy zone and the updated one. Also, I have tried with different instance types for both DB and EC2.

![parameters](https://user-images.githubusercontent.com/5468848/44834524-b97aae00-ac31-11e8-8afa-331941259614.png)

**Comment by michaelwittig** [comment]
How do you access WordPress (which Url)? This might be a duplicate of #68

**Comment by mr3k** [comment]
Hi @michaelwittig ! Are you totally right, this is a duplicate of #68 .

Short summary:
Make sure that the certificates are not issued for **only wildcard**. I updated the CF with a new certificate made on the naked domain which worked great. 

Thanks for a great template!
