### ISSUE TITLE
HA ecs/cluster with ASG 1:1:1 => EIP?

### ISSUE THREAD

**Issue by king7532** [widdix/aws-cf-templates#206]
Hi Guys,

I am trying to create a highly available ECS cluster with a single instance for a small project **without** an ALB (because they are pricey and this project will not have enough traffic). I am using the `ecs/cluster` template as my base and removing the following resources:
- LoadBalancer
- DefaultTargetGroup
- HTTP*
- ALBSecurity*
- AutoScalingGroupLifecycle*
- ScaleUp*
- ScaleDown*
- ContainerInstancesShortageAlarm
- ContainerInstancesExcessAlarm
- SchedulableContainers* (includes lambda)

I have configured the AutoScalingGroup to 1:1:1 and would like to know what are the best practices on assigning an EIP to an ECS instance, similar to the vpc-ssh-bastion template? Is there anything else I should know?

Thank you.

**Comment by michaelwittig** [comment]
Sounds good. Don't forget to add the iam permissions to enable the machine to assign the EIP.

I will close this issue since it is not directly related to the templates.
