### ISSUE TITLE
Jenkins agents not starting

### ISSUE THREAD

**Issue by SNeugber** [widdix/aws-cf-templates#211]
TemplateID: /jenkins/jenkins2-ha-agents
Region: eu-west-1

Hi!

I've set up Jenkins instance using your jenkins2-ha-agents template (as well as the /vpc/vpc-2azs and /vpc/vpc-ssh-bastion templates). Jenkins starts fine and connecting to it is also possible, but when I run a job it doesn't automatically create a new agent instance in the autoscaling group.

I have then also manually forced the creation of an agent in the autoscaling group but Jenkins doesn't pick it up as a build slave either.

Am I missing something?

Thanks for any help with this!

**Comment by michaelwittig** [comment]
Might be related to #210 ?

**Comment by SNeugber** [comment]
Ah, did not see that, my bad!

I'll recreate the cluster form the template in #210 and report back.

**Comment by SNeugber** [comment]
Great that fixed the autoscaling issue! The agent still doesn't show up as a build executor in Jenkins though :(
(Which also causes the build queue to not deplete, so it keeps adding more agents in the autoscaling group...)

**Comment by michaelwittig** [comment]
I noticed the performance problems as well... we will investigate. I also run a cluster for myself:) It seems to be related to a recent switch to Anazon Linux 2....

**Comment by SNeugber** [comment]
Fixed with #210
