### ISSUE TITLE
Jenkins - AWS Console Authentication?

### ISSUE THREAD

**Issue by matsev** [widdix/aws-cf-templates#22]
I have setup a Jenkins environment based on the `jenkins2-ha.json` template. Is it possible to configure Jenkins to delegate authentication to AWS? In other words, I would like to setup Jenkins so that a user can use the same username and password as he or she uses when logging in to the AWS Console.

**Comment by andreaswittig** [comment]
IAM is not intended to work as identity provider for 3rd party applications. Therefore you should not re-use your IAM users to log into Jenkins.

Possible solution: search for an identity provider supporting AWS and Jenkins user federation (e.g. with SAML) like https://auth0.com.

**Comment by matsev** [comment]
@andreaswittig Thanks. Do you think it is possible to setup a [Cognito User Pool](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) as identity provider for Jenkins? All hints and suggestions on what such an integration would look like are welcome.

**Comment by andreaswittig** [comment]
A Cognito User Pool is an option. But I haven't used a plugin/implementation for Jenkins so far.

You are probably looking for a Single-Sign-On solution for your team members/company. If so, I would have a look at auth0.com and their competitors as they offer integration endpoints for a lot of other services as well.
