### ISSUE TITLE
Jenkins fails to check out files stored on EFS using Git 

### ISSUE THREAD

**Issue by matsev** [widdix/aws-cf-templates#23]
After an initial successful configuration using the `jenkins2-ha.json` template, a Jenkins project has suddenly stopped working. The problem is that Jenkins fails to checkout the code from CodeCommit (see details in the copy from Jenkins' Console Output below). After some googling, I found [this Jenkins issue](https://issues.jenkins-ci.org/browse/JENKINS-37653) which is similar to my experience. In the comments there is a link to [Why you should not use Network File System (NFS) with Git or SVN](https://support.wandisco.com/index.php?/Knowledgebase/Article/View/182/5/why-you-should-not-use-network-file-system-nfs-with-SVN). Based on this information, I chose to clone the failing project (using "New Item" -> "Copy from", enter the name of my existing project in Jenkins). When I chose "Build Now" the new project checks out the files from Jenkins and builds the project without any problem, whereas the original project still fails due to the problems stated earlier. No changes was done to the Jenkins environment or Git credentials.

```
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sample_repo # timeout=10
Fetching upstream changes from https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sample_repo
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sample_repo +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sample_repo
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:799)
    at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1055)
    at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1086)
    at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
    at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:108)
    at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:57)
    at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:207)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://git-codecommit.us-east-1.amazonaws.com/v1/repos/sample_repo +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: Reference directory conflict: refs/remotes/origin/

    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1740)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1476)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
    at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
    at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:797)
    ... 8 more
ERROR: null
Finished: FAILURE
```

**Comment by michaelwittig** [comment]
hi @matsev 
I haven#t seen that error yet and I have multiple stacks running. Is the repo bigger? Any modifications to the template?

**Comment by matsev** [comment]
Hi @michaelwittig 
It is a very small repository as I am still evaluating this solution. I have made some modifications to the template, but nothing that concerns EFS. Basically I added S3 put access and CodeCommit access in the role used by the instance profile config:

```
{
    "Effect": "Allow",
    "Action": [
      "codecommit:GetBranch",
      "codecommit:GetRepository",
      "codecommit:GetTree",
      "codecommit:GitPull",
      "codecommit:ListBranches",
      "codecommit:ListRepositories"
  ],
  "Resource": "arn:aws:codecommit:us-east-1:*:*"
}
```

Additionally added a few lines to create a Jenkins .gitconfig file by adding the following lines to the `files` section of `AWS::CloudFormation::Init`:

```
"/var/lib/jenkins/.gitconfig": {
  "content": {"Fn::Join": ["", [
    "[credential]\n",
    "  helper = !aws codecommit credential-helper $@\n",
    "  useHttpPath = true\n",
    "[user]\n",
    "  email = jenkins@my-company.com\n",
    "  name = jenkins\n"
   ]]},
   "mode": "000444",
   "owner": "jenkins",
   "group": "jenkins"
}
```

**Comment by michaelwittig** [comment]
@matsev Let's see if this issue only applies to existing workspaces. Can you enable "Delete workspace before build starts" in the job.

**Comment by matsev** [comment]
@michaelwittig The job that I have is a Jenkins pipeline job (that does not have the "Delete workspace before build starts" configuration). However, the Jenkinsfile has the  `CleanBeforeCheckout` plugin configured:

```
stage ('Checkout') {
            checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    userRemoteConfigs: [[url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/my-repo]],
                    extensions: [
                            [$class: 'CleanBeforeCheckout']
                    ]
            ]
        }
```

**Comment by michaelwittig** [comment]
Two things are different to how I use it:
1. You use the https protocol. I usually use git over ssh
2. You use CodeCommit. I usually use GitHub
I also started to use Pipelines / Jenkinsfiles so that doesn't seem to be the problem.
