### ISSUE TITLE
ECS: Support the new ARN and resource ID format

### ISSUE THREAD

**Issue by pitkley** [widdix/aws-cf-templates#239]
TemplateID: `ecs/{cluster,service-cluster-alb,service-dedicated-alb}.yaml`
Region: any

-----

Given Amazon's [recent announcement](https://aws.amazon.com/blogs/compute/migrating-your-amazon-ecs-deployment-to-the-new-arn-and-resource-id-format-2/) about them changing the ECS ARNs and resource IDs, I tried opting in to the new IDs.

As documented in [the FAQs](https://aws.amazon.com/ecs/faqs/#Transition_to_new_ARN_and_ID_format), all instance, service and task ARNs that previously didn't include the cluster name now include it. This change is apparently so fresh, even the [CloudFormation `Name` attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#w2ab1c21c10d108c17b9b4) for the `AWS::ECS::Service` type returns the cluster name instead of the service name now.

While I was able to fix the CloudFormation issue by replacing e.g. [this](https://github.com/widdix/aws-cf-templates/blob/8c8bf5ebbbd8ead7acec6d54da48f74981fb091a/ecs/service-cluster-alb.yaml#L371) `!GetAtt 'Service.Name'` by `!Select [2, !Split ['/', !Ref Service]]`, I am not sure if there are other locations throughout the templates (specifically in the Lambda functions) where adaptation of any logic or parameter may be necessary. (Right now I unfortunately do not have the time to look into this any deeper.)

I don't see this ticket as a "please fix", but rather as a chance to point out to other users that the new ARNs are not yet supported, as well as a place for discussions on how to get the templates ready for the new ARNs and resource ID format.

The deadline set by Amazon for switching to the new ARNs and IDs is 2020-01-01, i.e. more than one year from now.

**Comment by michaelwittig** [comment]
Hi @pitkley If the name attribute returns the cluster name it sounds like a bug in CloudFormation? Can you open a support ticket with AWS?

**Comment by thovden** [comment]
I ran into this too today. `!GetAtt Service.Name` returns the cluster name. I don't use Widdix, but posting here to confirm there's an issue with CF.

**Comment by pitkley** [comment]
FYI, I just stumbled upon [an existing AWS forum post describing this exact issue](https://forums.aws.amazon.com/thread.jspa?threadID=294793). [According to AWS](https://forums.aws.amazon.com/message.jspa?messageID=882554#882554), their internal teams are aware of this, and the suggested workaround is to use the `!Select [_, !Split [...]]` construct I mentioned in [my initial post](https://github.com/widdix/aws-cf-templates/issues/239#issue-388660452).

**Comment by thovden** [comment]
Apparently the Select hack just stopped working: 


```
Template error: Fn::Select cannot select nonexistent value at index 2
```

**Comment by oanhnn** [comment]
I also encountered this problem. I couldn't create new service with template `ecs/service-cluster-alb.yaml` because with my AWS account, `!GetAtt 'Service.Name'` returns the cluster name instead of the service name.

```
ECS service doesn't exist: service/ECSClusterStack-XXX-Cluster-XXX/ECSClusterStack-XXX-Cluster-XXX (Service: AWSApplicationAutoScaling; Status Code: 400; Error Code: ValidationException; Request ID: 98a5985c-4102-11e9-9835-23433138c829)
```

**Comment by bsamuel-ui** [comment]
AWS has been aware of this since November. I [tidied up a test case I made](https://gist.github.com/bsamuel-ui/54ccff96a2a1f25d336a62ed152ca73d) and when they fix it, if you're opted in to long ARNs, you should see the correct outputs.

(Just ran it today, though, still not working.)

**Comment by dayyehm** [comment]
I have hard time getting this working with NLB using ingress controller :
https://kubernetes.github.io/ingress-nginx/deploy/#network-load-balancer-nlb

 ================================
kind: Service
apiVersion: v1
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    # Enable PROXY protocol
    #service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-07e3afcd4b7b5d644,eipalloc-0d9cb0154be5ab55d,eipalloc-0e4e5ec3df81aa3ea"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-061f4a497621a7179,subnet-001c2e5df9cc93960"
    # Ensure the ELB idle timeout is less than nginx keep-alive timeout. By default,
    # NGINX keep-alive is set to 75s. If using WebSockets, the value will need to be
    # increased to '3600' to avoid any potential issues.
    #service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https

**Comment by michaelwittig** [comment]
I'm closing this issue because we haven't received any feedback for a while.

**Comment by pitkley** [comment]
As @bsamuel-ui had posted in the related [AWS forum-thread](https://forums.aws.amazon.com/thread.jspa?threadID=294793), the issue in CloudFormation has been fixed. I have just verified that the `ecs/service-cluster-alb.yaml` stack works with the new ARNs enabled, so it seems like users of this stack should not expect any issues coming 2020-01-01.
