### ISSUE TITLE
Configuring $PATH for Jenkins?

### ISSUE THREAD

**Issue by matsev** [widdix/aws-cf-templates#24]
What is the preferred way of modifying the `$PATH` variable for the Jenkins user in the CloudFormation template?

I have setup a Jenkins environment based on the `jenkins2-ha.json` template. Now, I have added [asciidoctor](http://asciidoctor.org/)
 by configuring the `install` part of the template:

```
"rubygems" : {
  "asciidoctor" : []
},
```

When I login to the instance I can verify that it has been installed:
```
$ asciidoctor --version
Asciidoctor 1.5.4 [http://asciidoctor.org]
Runtime Environment (ruby 2.0.0p648 (2015-12-16) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)
```

However when I try to execute a bash command from Jenkins I find that
```
Running shell script
+ asciidoctor --version
[...]: asciidoctor: command not found
```

Some more investigation revealed that the `asciidoctor` has been installed to `/usr/local/bin/asciidoctor`, but the `$PATH` used by Jenkins is `/sbin:/usr/sbin:/bin:/usr/bin`. Consequently, what is the preferred way of adding `/usr/local/bin/` to Jenkins' `$PATH` in the CloudFormation template?

**Comment by michaelwittig** [comment]
@matsev does this work: http://stackoverflow.com/a/26965201/1897897 ?

**Comment by matsev** [comment]
@michaelwittig Yes, I tried that and it works fine. I was hoping to find a way to do it as part of the CloudFormation template to minimize manual configuration after the template has been deployed.

**Comment by michaelwittig** [comment]
@matsev I see. I don't know exactly where jenkins stores that information but you can have a look at /var/lib/jenkins/config.xml . If you find it there you can modify the file on startup. another way could be the provide the PATH in your job directly. 

So your bash job could look like this
```
export PATH=/usr/local/bin:$PATH
asciidoctor --version
```

I guess you could also add /usr/local/bin to the PATH when jenkins starts up. Should be somewhere in the init script.
