### ISSUE TITLE
Client Security Group for EC2 template?

### ISSUE THREAD

**Issue by bobics** [widdix/aws-cf-templates#240]
TemplateID: `ec2/ec2-auto-recovery.yaml`

I'm not sure if I'm using the templates incorrectly, but I noticed there's no parameter to wire up a Client Security Group Stack in `ec2-auto-recovery.yaml`. Should there be something similar to `ParentClientStack1` that was recently added to `ecs/cluster.yaml`?

**Comment by michaelwittig** [comment]
Ho @bobics Yes, it should be similar than what we did with the ECS cluster. Thanks for reporting this!
I opened a PR with the needed changes #241

**Comment by bobics** [comment]
Amazing, thanks so much!
