### ISSUE TITLE
Enable Multisite

### ISSUE THREAD

**Issue by hephalump** [widdix/aws-cf-templates#258]
I've successfully deployed the Wordpress-HA stack and everything is working as it should for a single site, however, I need a multisite network.

I've followed the Wordpress instructions for enabling multisite...  I edit the wp-config.php and the Network Setup appears as it should under the Tools menu in the admin.  I followed the network setup steps there, and created the network and then followed the tasks on screen and created an .htaccess file and again added some code to the wp-config.php file.  I restarted httpd.

Problem is, I'm not getting any option to create a network site. I'm running t2.large instances, and everything else is running perfectly but despite days of effort I can't get this multisite working.  Is this a limitation of this implementation or is there something else I'm missing here?

**Comment by andreaswittig** [comment]
I can't think of any limitations regarding a multisite network at the moment. We are using wp-cli to configure Wordpress within our scripts. Maybe https://developer.wordpress.org/cli/commands/core/multisite-install/ can help?

**Comment by hephalump** [comment]
@andreaswittig thank you for your reply.  I was trying to make the multisite network manually, which in theory should have worked, but it seems I was doing it incorrectly.  Apparently, manually doing it per the documents only works with a new installation BEFORE Wordpress is installed.  Even with the CLI I was having trouble installing multisite with `wp core multisite-install`.  This is actually the wrong command if you have an existing site.  If you have an existing site you have to convert it to multisite with `wp core multisite-convert` and then everything will work.

This would be an interesting launch configuration to add - option for single site, or multisite network, installation.

Thank you for your help and all you've done for the community; I have your AWS in Action book... Helped me a lot in my learning AWS :)
