### ISSUE TITLE
Wordpress: updating and installing plugins and themes

### ISSUE THREAD

**Issue by ialhashim** [widdix/aws-cf-templates#26]
First, thanks for sharing the templates!

I am trying to maintain a wordpress installation using your template, and I am wondering how I should go about keeping plugins and themes updated? 

The instructions mentions this limitation, and although it was straightforward to add plugins and themes during setup, I am not sure how to sustain such a stack. Is the template in its current form simply experimental?

**Comment by andreaswittig** [comment]
Updating core, plugins and themes need to move to the init-script of the EC2 instance.

**Comment by michaelwittig** [comment]
@ialhashim Does this answer your question?

**Comment by ialhashim** [comment]
Thanks for your response. So updating is maintained manually and we'd have to modify the init script each time?

I am not that familiar with working with CloudFormation, I tried updating the stack to install new plugins but obviously I was doing it wrong since the site reset as a fresh install.

In any case I am holding off working with the template until I better understand the process. Thanks again for sharing it!

**Comment by michaelwittig** [comment]
@ialhashim Yes. No manual updates. No changes to running machines.
As you said, when something is changed all EC2 instances are replaced. But in a way that does not affect your uptime (Rolling Updates).
