### ISSUE TITLE
Upgrade PHP version on EC2 and in Launch Config [amazon-cloudformation]

### ISSUE THREAD

**Issue by brandonjaie** [widdix/aws-cf-templates#274]
I'm trying to upgrade the PHP version on my EC2 instances from 7.0 to 7.2. I'd also like to upgrade the PHP version to 7.2 in the launch config so that when my EC2s scale, they'll have the upgraded version.

#amazon-cloudformation

**Comment by michaelwittig** [comment]
What's the stack's output value for `TemplateVersion` ?

The latest version of the templates use php 7.2.

**Comment by brandonjaie** [comment]
The stack we are using was created in 2017. We are using PHP 7.0.32

**Comment by michaelwittig** [comment]
You have to figure out the version as I described. Than update the stack for each major version by following the Migration Guides  on https://templates.cloudonaut.io/en/stable/ Until you arrive at thje latest 9.x version
