### ISSUE TITLE
Security: cloudtrail fails if using LogFilePrefix parameter

### ISSUE THREAD

**Issue by taasjord** [widdix/aws-cf-templates#277]
TemplateID: security/cloudtrail
Region: eu-central-1

If specifying the LogFilePrefix parameter (leaving ExternalBucket blank) the stack fails with error message: 

CREATE_FAILED | AWS::CloudTrail::Trail | Trail | Incorrect S3 bucket policy is detected for bucket: cloudtrail-trailbucket-cxfi46cn9r3v (Service: AWSCloudTrail; Status Code: 400; Error Code: InsufficientS3BucketPolicyException; Request ID: bd8de4bf-e57b-4b7e-9d62-4e11f005ff37)

I'm just guessing `TrailBucketPolicy.Resource: !Sub 'arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*'` does not include prefix and thus doesn't match. Works fine without setting LogFilePrefix, but took some time to figure out.

**Comment by taasjord** [comment]
See also: https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html#cloudtrail-add-change-or-remove-a-bucket-prefix

**Comment by michaelwittig** [comment]
hanks for reporting the bug. A PR with a fix is open and will be merged as soon as I get a review.
