### ISSUE TITLE
[security/account-password-policy] - HardExpiry always gets set to true

### ISSUE THREAD

**Issue by rch317** [widdix/aws-cf-templates#278]
--

TemplateID: security/account-password-policy
Region: us-east-2

HardExpiry always gets marked as "true" regardless of setting the value to "false".  It looks like the value passed to Boolean is being evaluated as a string, rather than a boolean:

```
$ node
> Boolean('false')
true
> Boolean(false)
false
```

**Comment by michaelwittig** [comment]
Thanks for reporting the bug. A PR with a fix is open and will be merged as soon as I get a review.
