### ISSUE TITLE
Error Creating vpc-4azs

### ISSUE THREAD

**Issue by devotoare** [widdix/aws-cf-templates#28]
Had a problem creating a stack with the vpc-4azs template. The first error I received was "Template error: Fn::Select cannot select nonexistent value at index 3" on the "SubnetDPrivate" Logical ID. From there it kind of went downhill. I managed to create a 2 zone vpc using your template and used the exact same parameter values for both. I have attached a zip contaning a csv with the full output of the Events tab in the console.

Any help would be appreciated.

[vpc-4azs-error.zip](https://github.com/widdix/aws-cf-templates/files/503453/vpc-4azs-error.zip)

**Comment by michaelwittig** [comment]
What's your selected aws region?

**Comment by devotoare** [comment]
US West (Oregon)

**Comment by michaelwittig** [comment]
This region only has 3 Availability Zones so you can only launch the 2azs or 3azs template.

You can check the availability zones in a region via the AWS CLI:
```
aws ec2 describe-availability-zones --region us-west-2
{
    "AvailabilityZones": [
        {
            "State": "available", 
            "RegionName": "us-west-2", 
            "Messages": [], 
            "ZoneName": "us-west-2a"
        }, 
        {
            "State": "available", 
            "RegionName": "us-west-2", 
            "Messages": [], 
            "ZoneName": "us-west-2b"
        }, 
        {
            "State": "available", 
            "RegionName": "us-west-2", 
            "Messages": [], 
            "ZoneName": "us-west-2c"
        }
    ]
}
```

US East (N. Virginia) (us-east-1) has 4 AZs.
