### ISSUE TITLE
Depreciated Node.js 6.10 in ECS cluster

### ISSUE THREAD

**Issue by zajacm** [widdix/aws-cf-templates#292]
TemplateID: `ecs/cluster.yaml`
Region: `eu-west-1`

ECS cluster [uses Node.js 6.10](https://github.com/widdix/aws-cf-templates/blob/master/ecs/cluster.yaml#L1411) runtime for SchedulableContainers lambda function which is depreciated.

Email from AWS;

> Hello,
> 
> Your AWS Account currently has one or more Lambda functions using the node.js 6.10 runtime. The Node Foundation has previously published that node.js 6.x "Boron" will be declared End-of-Life (EOL) on April 2019 [1], and will stop receiving bug fixes, security updates, or performance improvements. Per the AWS Lambda runtime support policy [2], language runtimes that have reached their EOL are deprecated in AWS Lambda.
> 
> Invokes for functions configured to run on node.js 6.10 will continue to work normally, however the ability to create new Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30 2019

**Comment by michaelwittig** [comment]
see #291

**Comment by zajacm** [comment]
Ok, thanks
