### ISSUE TITLE
Change EFS throughput mode from bursting to provisioned

### ISSUE THREAD

**Issue by troydieter** [widdix/aws-cf-templates#324]
Please change the EFS created mount from bursting to provisioned. Over time, the EFS mount is quickly depleted of burst credits due to tag .xml files from builds. This causes massive file-wait on the EFS mount and completely degrades Jenkins performance. 1Mbit/s provisioned EFS mount created is still extremely affordable and ensures throughput.

>        - Key: Name
>         Value: 'jenkins-master-storage'
>       PerformanceMode: generalPurpose
>   MasterStoragePercentIOLimitTooHighAlarm:
>     Condition: HasAlertTopic
>     Type: 'AWS::CloudWatch::Alarm'
>     Properties:
>       AlarmDescription: 'Average IO utilization over last 10 minutes higher than 80%'
>       Namespace: 'AWS/EFS'
>       MetricName: PercentIOLimit
>       Statistic: Average
>       Period: 600
>       EvaluationPeriods: 1
>       ComparisonOperator: GreaterThanThreshold
>       Threshold: 80
>       AlarmActions:
>       - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
>       Dimensions:
>       - Name: FileSystemId
>         Value: !Ref MasterStorage
>   MasterStorageBurstCreditBalanceTooLowAlarm:
>     Condition: HasAlertTopic
>     Type: 'AWS::CloudWatch::Alarm'
>     Properties:
>       AlarmDescription: 'EFS file system is running out of burst credits. You can expect a significant performance drop in the next hour.'
>       Namespace: 'AWS/EFS'
>       MetricName: BurstCreditBalance
>       Statistic: Average
>       Period: 600
>       EvaluationPeriods: 1
>       ComparisonOperator: LessThanThreshold
>       Threshold: 192416666667 # 192 GB in Bytes (last hour where you can burst at 100 MB/sec)
>       AlarmActions:
>       - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
>       Dimensions:
>       - Name: FileSystemId
>         Value: !Ref MasterStorage
>       ThroughputMode: provisioned
>       ProvisionedThroughputInMibps: 1
>   MasterStorageMountTargetA:
>     Type: 'AWS::EFS::MountTarget'
>     Properties:

**Comment by michaelwittig** [comment]
Hi @troydieter 

Can you confirm that a CloudWatch Alarm was triggert?
Can you create screenshots of your EFS metrics and add them to the ticket?

Thanks
Michael

**Comment by troydieter** [comment]
Hi @michaelwittig -

Unfortunately it seems that someone manually deleted the CloudWatch alarm for EFS burst credits, therefore we never received any alarms.

Here is our burst credit Cloudwatch metrics 
![2019-06-04 09_52_04-CloudWatch Management Console](https://user-images.githubusercontent.com/3689896/58884701-e66f5c00-86ae-11e9-8507-98e0e5236a59.png)

Here is support's response:

> I understand that there is high CPU wait times on your instance and you suspect that reason behind it is because of EFS mount “fs-3371dcd2”.
> 
> I have noticed two possible reasons for performance issues.
> 
> 1.      EFS is one reason. Using internal tools, I have investigated EFS and noticed that the burst balance of the EFS is reduced to 0 because maximum permitted throughput is being hit constantly which depleted the burst credits and currently EFS is running on baseline throughput [1] .
> ==================================
> BurstCreditBalance:
> REDACTED
> 
> TotalIOBytes: (throughput)
> REDACTED
> ===================================
> 
> Throughput on Amazon EFS scales as a file system grows. Because file-based workloads are typically spiky - driving high levels of throughput for short periods of time, and low levels of throughput the rest of the time - Amazon EFS is designed to burst to high throughput levels for periods of time. It uses a credit system to determine when file systems can burst. Each file system earns credits over time at a baseline rate that is determined by the size of the file system, and uses credits whenever it reads or writes data. The baseline rate is 50 MiB/s per TiB of storage (equivalently, 50 KiB/s per GiB of storage).
> The current size for EFS ID fs-3371dcd2 in region us-east-1 is 3.08 GiB, thus providing a baseline throughput of 154.0527 KiB/s. Considering your usage from the last 14 days, the suggested size for your file system is 10 GiB, which would provide a baseline throughput of 0.49 MiB/s.
> credits earned = baseline performance - actual throughput
> 
> 300 kbps =150 kbps – 450 kbps 
> 
> So, when throughput was 450 kbps 300kb of credits per second have been consumed constantly this usage has depleted the burst credits.
> Currently you can get desired throughput by changing EFS mode from bursting to provisioned with throughput of 500 kbps or higher (as this is the average throughput in past 14 days). I recommend to increase the EFS size so that base line will be 500 kbps and switch back to bursting mode as with bursting mode, we can throttle to a higher throughput when required.
> Please note that switching back and forth from provisioned to bursting mode can only be done once in every 24 hours.
> 
> You can increase your file system size by either adding files to it or by creating dummy files; should you need to create them, you can do so with the ‘dd’ tool, as in the example below:
> 
> dd if=/dev/zero of=/path/to/efs/dummyfile bs=1M count=1024
> 
> The command above will create a dummy file on /path/to/efs called ‘dummyfile’ with a size of 1 GiB. Please adjust the file path and name accordingly, as well as the ‘count’ parameter if you wish to create a larger file. Please note that you’ll be charged for the additional space used, following our current pricing policy (https://urldefense.proofpoint.com/v2/url?u=https-3A__aws.amazon.com_efs_pricing_&d=DwIFaQ&c=ZFvrBgGA-mo-lsN3Ia6QLQ&r=FWGiaE0NGdxuf2_VPFe9YA&m=XwTLvPXN11RWwOB452gbXBinQgKmL-ZJr_Sb2J7i5ho&s=7hJ1Q0TQkKluN3sOyB-MuOuGQS8LBankzRVRb9CqIEU&e=  ) more information on Throughput Scaling at EFS, please refer to the corresponding section of the EFS documentation, found at https://urldefense.proofpoint.com/v2/url?u=http-3A__docs.aws.amazon.com_efs_latest_ug_performance.html-23bursting&d=DwIFaQ&c=ZFvrBgGA-mo-lsN3Ia6QLQ&r=FWGiaE0NGdxuf2_VPFe9YA&m=XwTLvPXN11RWwOB452gbXBinQgKmL-ZJr_Sb2J7i5ho&s=8PWaNidb0avWDZcmNLnuqMsH574pq2tNROGlpw0TaKw&e= 
> 
> 2.      Investigating Instance console logs I noticed the following error “too much work for irq4”. This might be one reason for performance issue as EC2 instances may throttle the serial console output if the instance is sending too much data to the serial console.  If this throttling occurs, the instance may hang until the message can be written to the console, leading to poor performance and potentially crash.
> 
> This can be checked in dmesg by running the following command 
> dmesg | grep "too much work for irq4"
> 
> To avoid throttling, the instance should be configured to send less data to the serial console. The majority of console messages are sent via syslog services, primarily rsyslogd.
> 
> In /etc/rsyslogd.conf (/etc/rsyslog.conf in Amazon Linux), add the following line under the global directives section.  If a klogConsoleLogLevel line is present, modify the existing value instead.
> $klogConsoleLogLevel 4
> 
> After making the change to rsyslogd.conf (rsyslog.conf in Amazon Linux), you must reload the configuration for the change to take effect
> $ sudo service rsyslog reload
> 
> if the application doesn't use rsyslog demon please configure application in such a way that it logs data to a file and not to the serial console.
> 
> For high volume logging, we recommend forwarding logs to a log management service such as CloudWatch Logs instead of logging application messages directly to the serial console.  The netconsole system can be used to help debug kernel level issues which would otherwise generate too much traffic to the serial console, or when the serial console is otherwise not suitable.
> 
> 
> If you have any questions or concerns please reply back to the case I will be happy to assist you
> 
> Resources:
> [1] https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.aws.amazon.com_efs_latest_ug_performance.html-23bursting&d=DwIFaQ&c=ZFvrBgGA-mo-lsN3Ia6QLQ&r=FWGiaE0NGdxuf2_VPFe9YA&m=XwTLvPXN11RWwOB452gbXBinQgKmL-ZJr_Sb2J7i5ho&s=eggzMRgYzTDEwUmvdJQGx16-7KPZrsmPBvzpbgtTbvo&e=

**Comment by michaelwittig** [comment]
see #327
