### ISSUE TITLE
ECS Cluster Auto Scaling Error

### ISSUE THREAD

**Issue by jpcbarros** [widdix/aws-cf-templates#331]
TemplateID: ecs/cluster.yaml
Region: us-east-1 or us-west-2

Can't deploy the ECS Cluster due to failed Auto Scaling:
`
CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup | AutoScalingGroup | Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
`

Apparently the problem is due to an error on SchedulableContainers lambda that I could not find the cause to:

Lambda log:
`
{
    "errorMessage": "Container instance cannot be empty.",
    "errorType": "InvalidParameterException",
    "stackTrace": [
        "Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)",
        "Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)",
        "Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "/var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)",
        "Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)"
    ]
}
`

I am running the template with the following parameters:
`
ContainerExcessThreshold | 10 | -
ContainerMaxCPU | 128 | -
ContainerMaxMemory | 128 | -
ContainerShortageThreshold | 2 | -
DesiredCapacity | 1 | -
DrainingTimeoutInSeconds | 60 | -
IAMUserSSHAccess | false | -
InstanceType | t2.large | -
KeyName | production | -
LoadBalancerCertificateArn | ... | -
LoadBalancerIdleTimeout | 60 | -
LoadBalancerScheme | internet-facing | -
LogsRetentionInDays | 14 | -
ManagedPolicyArns | - | -
MaxSize | 2 | -
MinSize | 1 | -
ParentAlertStack | alert | -
ParentAuthProxyStack | - | -
ParentClientStack1 | - | -
ParentClientStack2 | - | -
ParentClientStack3 | - | -
ParentS3StackAccessLog | - | -
ParentSSHBastionStack | bastion | -
ParentVPCStack | vpc | -
StopContainerTimeoutInSeconds | 120 | -
SubnetsReach | Private | -
SystemsManagerAccess | false | -
`

**Comment by michaelwittig** [comment]
Hi! I see that your `SubnetsReach` is set to `Private`. Have you deployed a nat gateway in each private subnet?

**Comment by jpcbarros** [comment]
@michaelwittig ,

I didn't. Let me try redeploying this application with the NAT Gateway and see how it goes. For some reason I figured this was already being created in the template vpc/vpc-2azs.yaml, but its not.

Be right back :)

**Comment by jpcbarros** [comment]
@michaelwittig adding the NAT Gateway solved the issue. Do you want me to make a PR to make the docs somehow more clear about that dependency when using SubnetsReach as Private?

**Comment by michaelwittig** [comment]
the `SubnetsReach` parameter comes with the following description:
Should the cluster have direct access to the Internet or do you prefer private subnets with NAT?

Not sure how we can document this more clearly?
