### ISSUE TITLE
Support for Aurora postgresql serverless

### ISSUE THREAD

**Issue by jvolkman** [widdix/aws-cf-templates#350]
TemplateID: `state/rds-aurora-serverless.yaml`
Region: any

The Aurora serverless template only supports mysql. Serverless support for postgresql now exists under then `aurora-postgresql` engine (see query below). It seems that the serverless template will need something similar to`EngineMap` from `state/rds-aurora.yaml`.

Are there plans to add support for postgresql?

```shell
$ aws rds describe-db-engine-versions --engine aurora-postgresql --query 'DBEngineVersions[?contains(SupportedEngineModes,`serverless`)]'
[
    {
        "Engine": "aurora-postgresql",
        "EngineVersion": "10.7",
        "DBParameterGroupFamily": "aurora-postgresql10",
        "DBEngineDescription": "Aurora (PostgreSQL)",
        "DBEngineVersionDescription": "Aurora PostgreSQL (compatible with PostgreSQL 10.7)",
        "ValidUpgradeTarget": [],
        "SupportsLogExportsToCloudwatchLogs": false,
        "SupportsReadReplica": false,
        "SupportedEngineModes": [
            "serverless"
        ],
        "SupportedFeatureNames": [
            "s3Import"
        ],
        "Status": "available"
    }
]
```

**Comment by michaelwittig** [comment]
we already have a module for that: https://github.com/cfn-modules/rds-aurora-serverless-postgres
this can be used as a basis to port the aurora-serveress template without running into all the pitfalls

**Comment by jvolkman** [comment]
Ah, thanks for the pointer. I'll take a look at going down the cfn-modules route.

**Comment by michaelwittig** [comment]
I started working on the template: https://github.com/widdix/aws-cf-templates/pull/351
