### ISSUE TITLE
Problems deploying fargate-service via CLI

### ISSUE THREAD

**Issue by prolic** [widdix/aws-cf-templates#355]
I'm using the fargate sevice template (https://github.com/widdix/aws-cf-templates/blob/master/fargate/service-cluster-alb.yaml). When I use the AWS Website to create the stack, there is no problem and the stack gets created / updated.
But when I use the CLI (aws cloudformation update-stack) the stack will not get created / updated. Instead I receive this error: `Service arn:aws:ecs:{region}:{account-id}service/pl-production-api-Service-1EXZ05UWXUYPV did not stabilize.`
Do you have any idea why this happens? I double and triple checked all parameters and I'm sure there is no wrong parameter given via CLI.

**Comment by michaelwittig** [comment]
can you check your ecs service while it's created. i assume that tasks are started and fail for some reason (check out the stopped / failed tasks!). The ECS service will restart tasks for a long time until it gives up.

**Comment by prolic** [comment]
![Screenshot-18](https://user-images.githubusercontent.com/394428/66405742-f2eb2480-e9c0-11e9-9e16-92d06d50dae3.png)

Those are coming and replaced by new tasks after a couple of seconds.

**Comment by prolic** [comment]
in stopped tasks I see `STOPPED (Task failed to start)`

**Comment by michaelwittig** [comment]
Do you fetch your Docker images from ECR or Docker Hub? If Docker Hub, is this a private image?

**Comment by michaelwittig** [comment]
1. Does the ECR repo exist?
2. Is the repo in the same account and region than your stack?
3. Can you share the full Docker image name that you pass to CloudFormation?

**Comment by prolic** [comment]
docker image name..... I only gave the image name and version without the host (`{account-id}.dkr.ecr.us-east-1.amazonaws.com`).

Damn it, what a stupid mistake! Thank you soooo much for your help! And of course for those awesome cloudformation templates!
