### ISSUE TITLE
Elasticsearch can't replace unless it is explicitly renamed

### ISSUE THREAD

**Issue by zfLQ2qx2** [widdix/aws-cf-templates#356]
TemplateID: state/elasticsearch

Because the template is making us choose a name for the ES domain, cfn has is unable to replace it when necessary, we have to manually rename the domain to do so. I tried to remove the domainname parameter but that gets into a circular reference between the monitors and cloudwatch alerts. I am wondering if there is an easy tweak to allow cfn to pick the domain name.

**Comment by michaelwittig** [comment]
You could try the following (which requires a replacement of the resource).

1. Change line https://github.com/widdix/aws-cf-templates/blob/master/state/elasticsearch.yaml#L153 to `Resource: '*'
2. Remove line https://github.com/widdix/aws-cf-templates/blob/master/state/elasticsearch.yaml#L154
3. Remove line https://github.com/widdix/aws-cf-templates/blob/master/state/elasticsearch.yaml#L64 to 66

**Comment by michaelwittig** [comment]
I'm closing this issue because we haven#t received any feedback for a while.
