### ISSUE TITLE
VPC: Invalid availability zone

### ISSUE THREAD

**Issue by fiducioso-dan** [widdix/aws-cf-templates#36]
Apparently us-east-1b isn't a valid AZ for creating subnets in my account.

```
CREATE_FAILED	AWS::EC2::Subnet	SubnetBPrivate	Value (us-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1d, us-east-1e, us-east-1a, us-east-1c.
```

**Comment by andreaswittig** [comment]
We are using Fn::GetAZs to determine a valid availability zone. So this should not happen. :)

Which template are you using? The newest version?

**Comment by fiducioso-dan** [comment]
I clicked the Launch Stack button on [this page](https://cloudonaut.io/vpc-templates-for-aws-cloudformation/) for 3 AZs.

The AZ us-east-1b is a valid AZ in my account, but I cannot create new subnets in that AZ. It seems that `Fn::GetAZs` lists all AZs, not just the ones that subnets may be created in, see [this SO question](http://stackoverflow.com/questions/21390444/is-there-a-way-for-cloudformation-to-query-available-zones-for-subnet-creation).

**Comment by andreaswittig** [comment]
Fine, didn't expect that behavior. Any ideas for a solution, that is still simple to use?

**Comment by fiducioso-dan** [comment]
I don't think there's any reasonable way to detect and skip AZs that are invalid for VPC subnets in CloudFormation.

Probably the least painful solution is to add a parameter of type `List<AWS::EC2::AvailabilityZone::Name>` and let users pick which AZs to use.

**Comment by michaelwittig** [comment]
For the EC2-VPC platform, the Fn::GetAZs function returns only Availability Zones that have a default subnet unless none of the Availability Zones has a default subnet; in that case, all Availability Zones are returned.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html

**Comment by michaelwittig** [comment]
@fiducioso-dan can you check if you have a default vpc in the region where you deploy the stack? You will find the VPCs here: https://console.aws.amazon.com/vpc/home#vpcs:
There is a **Default VPC** column to indicate if the VPC is a default vpc.

**Comment by Ruprect** [comment]
@michaelwittig Yes I do have a default VPC:

![image](https://cloud.githubusercontent.com/assets/883620/20309354/e6fde7da-ab47-11e6-8d9d-25c7581f5db8.png)

Should I reference that instead of 10.200.0.0/16 that I have entered as a value for when I ran the template?

**Comment by btsuhako** [comment]
Just another datapoint for troubleshooting: I was able to successfully launch the 3 AZ template into the `us-west-2` region in Oregon. I did not have a default VPC resource before doing so.

**Comment by michaelwittig** [comment]
@fiducioso-dan  do you have developer, business or enterprise support in the AWS account where the template fails? I can not reproduce the issue in any of my accounts where I have a support plan. Would be interested in what the AWS Support has to say.

**Comment by michaelwittig** [comment]
@fiducioso-dan the issue in #37 was that there was a default vpc but not a subnet in each availability zone. Can you plese double check if you have a subnet in each AZ for the default vpc.

**Comment by mfonsen** [comment]
With classic AWS account without default VPCs I ran into this issue as well. 

Contacted AWS support and they confirmed that there's no way to automatically determine available AZs for subnet creation in CloudFormation. Their suggestion was similar to SO answer mentioned above which requires manual steps.
