### ISSUE TITLE
Template error: Fn::Select cannot select nonexistent value at index 1

### ISSUE THREAD

**Issue by Ruprect** [widdix/aws-cf-templates#37]
I try to deploy the script to my existing deployment zone (Ireland), but get the error:

> AWS::EC2::Subnet	SubnetBPrivate	Template error: Fn::Select cannot select nonexistent value at index 1

I already have a subnet setup on Ireland, so for testing purposes I deployed the script to the Frankfurt region. Here it had no problems deploying, and worked like a charm, I even deployed the script a second time, to another subnet. And both were setup properly.

For testing purposes i disabled the rollback function:

![image](https://cloud.githubusercontent.com/assets/883620/20307307/28056900-ab3f-11e6-918f-8913b435c340.png)

**Comment by Ruprect** [comment]
Okay, since I ran this template as part of setting up Wordpress (https://github.com/widdix/aws-cf-templates/tree/master/wordpress), a deployment to Frankfurt zone is not a solution.

Because EFS is not supported by Frankfurt region:
![image](https://cloud.githubusercontent.com/assets/883620/20308501/7da4a9d4-ab44-11e6-84c2-453aa4bfdcaf.png)

So any help in executing the vpc-2azs.yaml is appreciated.

**Comment by michaelwittig** [comment]
I think thisissue is at least related to #36 

@Ruprect can you check if you have a default vpc in the region where you deploy the stack? You will find the VPCs here: https://console.aws.amazon.com/vpc/home#vpcs:
There is a Default VPC column to indicate if the VPC is a default vpc.

**Comment by Ruprect** [comment]
I have added an answer to #36 - I do have a Default VPC.

**Comment by michaelwittig** [comment]
@Ruprect do you have developer, business or enterprise support in the AWS account where the template fails? I can nor reproduce the issue in any of my accounts where I have a support plan. Would be interested in what the AWS Support has to say.

**Comment by Ruprect** [comment]
I will contact support with this issue, and relay the answer here

**Comment by Ruprect** [comment]
Okay. The issue has been solved, the problem was the the two other availability zones (eu-west-1a and eu-west-1b) did not have a default subnet. And since I only deployed to eu-west-1c, I had not experienced any problems.

For reference, here is the reply from Amazon support:

> Thanks for contacting AWS Premium Support!
> 
> I understand you have a template which launches in the Frankfurt region but not the Dublin region.
> 
> I've been able to launch that template myself without issue so I've been looking over your account for any possible cause.
> 
> I notice that the first resource to fail creation is SubnetBPublic. I see that this makes use of the function !GetAZs. !GetAZs will return all AZs in the account which have a 'Default' subnet in them. The issue is if you have deleted the subnet from a VPC that was marked as default, that AZ won't be returned by GetAZs here. See further info on this here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getavailabilityzones.html
> 
> Looking at your account, I see that there is a default subnet only in eu-west-1c, so only that AZ will be returned to !GetAZs. Then !Select [1, !GetAZs ''] is trying to access a second element that does not exist.
> 
> The solution to this is to create at least one new subnet in each AZ. This should be marked as default automatically.
> 
> Alternatively if you wish I can manually intervene and set existing subnets of your choice as default for a given AZ. If you wish for me to do this please provide the subnet IDs and the respective AZ which you want them to be the default for.
> 
> I hope this is clear, but if you have any questions or concerns don't hesitate to let me know.

**Comment by michaelwittig** [comment]
thanks for forwarding this.

**Comment by btbensoft** [comment]
Yes Thanks you !

To clarify create default subnet

```
> aws ec2 create-default-subnet --availability-zone eu-west-3a
> aws ec2 create-default-subnet --availability-zone eu-west-3b
> aws ec2 create-default-subnet --availability-zone eu-west-3c
```
