### ISSUE TITLE
CloudFormation: The request could not be satisfied.

### ISSUE THREAD

**Issue by Ruprect** [widdix/aws-cf-templates#39]
After using the 2az template, and then the WordPress template, as described here (https://github.com/widdix/aws-cf-templates/tree/master/wordpress) i get the following error from my endpoint:

![image](https://cloud.githubusercontent.com/assets/883620/20339601/9cd64e72-abdd-11e6-8db4-b0a3c31cee46.png)

As I have experienced problems on my other account (as mentioned in #37 and #36), this has been setup on another account.

A2Z launch:
![image](https://cloud.githubusercontent.com/assets/883620/20339696/15f9f650-abde-11e6-89ab-54710273d3a6.png)

Wordpress launch:
![image](https://cloud.githubusercontent.com/assets/883620/20339723/3a20f4de-abde-11e6-90fa-db182d0d850e.png)

The endpoint, as obtained from the Output tab:
https://d1rv0uqa4nxmuh.cloudfront.net

**Comment by michaelwittig** [comment]
Hi @Ruprect sorry for the late response. Is this still an issue that we can investigate? Or is the stack already deleted?

**Comment by musamamasood** [comment]
I am facing same issue. @Ruprect have you found it? 

@michaelwittig I am facing same issue and it rollback http://prntscr.com/end132

**Comment by michaelwittig** [comment]
@musamamasood Your issue is different. Can you check the logs in Cloud Watch Logs. For some reason the EC2 instance is not able to bootstrap the app.

**Comment by musamamasood** [comment]
Sorry, I figure out but further got same message now: https://d1u14siuv00o9p.cloudfront.net/

Thank you so much for quick reply.

**Comment by michaelwittig** [comment]
1. What was wrong? Hod do you solved the issue?
2. Can you check the logs in CloudWatch Logs. They likely tell us what is wrong.

**Comment by musamamasood** [comment]
1- It's security inbound rule issue. 
2- Okay. Let me review the CloudWatch Logs first.
