### ISSUE TITLE
jenkins/jenkins2-ha keep showing reverse proxy set up is brokenreverse proxy set up is broken

### ISSUE THREAD

**Issue by manishki** [widdix/aws-cf-templates#398]
TemplateID: (check the `TemplateID` output of your stack, e.g. `jenkins/jenkins2-ha`)
Region: (e.g. `us-west-2`)

Manage Jenkins page keep showing the message 
```It appears that your reverse proxy set up is broken.```
Even though there is no proxy configuration I did. There is no proxy configuration inside the Jenkins master instance. 
Configuration System page **Jenkins URL** always showing _403 Forbidden_ I think the issues are also related to the proxy configuration. In case anyone knows there something wrong with Jenkins's master configuration?

**Note:** There is nothing wrong showing in the Jenkins logs or any of the OS logs. 

Thanks 
Manish

**Comment by michaelwittig** [comment]
Hi Manish

1. Have you modified the CloudFormation template?
2. Is this error popping up directly after you created the stack?

**Comment by manishki** [comment]
Hi Michael,
Thanks for the response. 
1. Have you modified the CloudFormation template?
**Ans:-** _No modification expect the use of my custom VPC and subnet id._ 
2. Is this error popping up directly after you created the stack?
**Ans:-** _This error started showing after creating the stack and launching the Jenkins master first time. The error keeps popping in my Jenkins master configuration_  

Thanks 
Manish

**Comment by michaelwittig** [comment]
I can not replicate your issue with the non-modified template. Could you try the original template and see if that works?

**Comment by manishki** [comment]
It is working fine. I am able to resolve the issues.

Thanks 
Manish
