### ISSUE TITLE
EFS Not supported in ap-southeast-2 (Sydney)

### ISSUE THREAD

**Issue by simon-morgan** [widdix/aws-cf-templates#40]
@andreaswittig and @michaelwittig thanks so much for posting your templates - they are excellent. Glad to see them in yaml.

I run your templates unchanged from a master stack template which works well.

However, for your Jenkins templates I get failures on account of EFS not being supported in Sydney.  Do you happen to have versions without EFS?

**Comment by andreaswittig** [comment]
@simon-morgan Have a look at previous versions of the template. They are using S3 for user uploads and restrict installing/updating themes, plugins, and updates.

**Comment by simon-morgan** [comment]
@andreaswittig thanks for a quick update.  I might be missing something but the earliest version of the jenkins template I can find is [here](https://github.com/widdix/aws-cf-templates/commit/fc83724c8c7cb4684bc600c2afee77838c71efe6#diff-2fe8961e9303da7ffe7114bf1bd90900) - it still uses EFS.  Can you provide a link to a version of the jenkins template you are referring to? Thanks again for your help.

**Comment by michaelwittig** [comment]
hi @simon-morgan I guess @andreaswittig mixed this up with the WordPress template. There we had a non EFS version in the past.
EFS is a very important part of the template os it is not easy to replace it. At the moment only two options are available: run a region where efs is supported ( https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ ) or wait until it becomes available...

**Comment by simon-morgan** [comment]
@michaelwittig thanks for the update. I'll adapt the template for use in apac. Thanks again.
