### ISSUE TITLE
How to update opcache configuration?

### ISSUE THREAD

**Issue by pratikdhody** [widdix/aws-cf-templates#407]
https://github.com/aws-samples/aws-refarch-wordpress recommends updates to opcache but it doesn't specify where?
I've updated on the ec2 instances at /etc/php.d/10-opcache.ini but I can't see the updates in https://www.url/opcache-instanceid.php
Thoughts?

**Comment by michaelwittig** [comment]
There is a reason why the issue template asks you for the template...
