### ISSUE TITLE
Private Subnet ACL (Name vs. Implementation)

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#427]
TemplateID: `vpc/vpc-2azs` (but probably others `vpc-*azs`)
Region: `us-east-1`

The ACL Entries for the Private networks are labeled `NetworkAclEntryInPrivateAllowVPC` and `NetworkAclEntryOutPrivateAllowVPC` (note `VPC`) but the CIDR block is `0.0.0.0/0` (like the `*PublicAllowAll` entries).  It would be helpful to users if the name and implementation aligned.  

My best guess is that the rules were originally restricted to the VPC and later changed to support a NAT Gateway.  

- The simplest solution is to rename them both to `All` to make sure the semantics are right. 
- However, I also wonder if it's possible to default to the actual VPC CIDR and change the ACL as part of the `vpc-nat-gateway` template.  Thus the template replaces the ACL rule for `Subnet*Private` if and only if a NAT Gateway (or instance) is added.  This seems consistent with the addition of the `Route` as part of this template.

**Comment by michaelwittig** [comment]
I agree that the logical id is out of sync with the rule. I tested the rename and CloudFormation was able to recreate the rule without issues (I was concerned because of the `RuleNumber`).

I added the fix to the IPv6 PR #426 which will be merged soon

**Comment by michaelwittig** [comment]
We strongly believe in not using ACLs to restrict network traffic in AWS.
Security Groups are by far the better option.
Working with SGs only makes things much easier to reason about .
