### ISSUE TITLE
Alternate domain name error during Cloudfront config...

### ISSUE THREAD

**Issue by kcheney** [widdix/aws-cf-templates#452]
TemplateID: wordpress/wordpress-ha-aurora
Region: us-west-2

The DNS Zone template has the apex domain defined as example.com. The Wordpress template is consistently failing due to the following error: 

_The certificate that is attached to your distribution doesn't cover the alternate domain name (CNAME) that you're trying to add. For more details, see: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-requirements (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidViewerCertificate; Request ID: XXXXXXX)_

It fails if deployed in US-East-1 as well as US-West-2. I have tried to create a certificate using ACM using a DNS Zone without any CNAME subdomain to domain entries such as wildcard and generating a similar certificate hoping Cloudfront would accept it, but no such luck. Do I need to create a Cert using the CLI rather than through the console?

Thanks for the assistance.

**Comment by michaelwittig** [comment]
related to #443 ?

**Comment by michaelwittig** [comment]
closed due to inactivity
