### ISSUE TITLE
state/elasticache-redis Memory Usage Alert?

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#461]
TemplateID: `state/elasticache-redis`
Region: `us-east-1`

For reasons that I haven't bothered to diagnose (and won't if they don't recur), my Redis node ended up completely full (i.e. 100% Out of Memory).  I use Redis for async tasks and my tasks often create more tasks so I was locked in a situation where I could make no progress.

I didn't notice any alert notifying me of this condition.  I assume it's a pretty critical threshold so I wanted to float the idea of adding one.

**Comment by ambsw-technology** [comment]
It looks like `DatabaseMemoryUsagePercentage` is the right [metric](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.Redis.html).

**Comment by michaelwittig** [comment]
I like the idea. See #463 

I wanted to change the way alarms are created a couple of times for all templates to allow:
* modifying the thresholds
* disabling alarms entirely

**Comment by ambsw-technology** [comment]
The key thing I'd do is preserve the units in the descriptions.  For example, on `Node1ReplicationLagTooHighAlarm` use something like `Average replication lag over last 10 minutes higher than specified threshold (in seconds)` rather than `Average replication lag over last 10 minutes too high`.  Similarly, the `EvictionsThreshold` needs to state the period (looks like it's over 10 minutes).

Food for thought:

 - If `Memory` and `Evictions` were not compatible (I think they are) how would you pick the default and documentation?
 - Are there cases where -1 through MAX_VALUE won't work.  CPU/Memory > 0% is logically valid, but odd.  Are there cases where the value cannot be zero (or below a specific number).
 - Are there good use cases to change the statistic, periods, and/or evaluation periods?

The default alarms really make me feel like I'm following good best practices.  At the same time I wonder if you should go a different direction:

 - Include a set of default alarms that are sane but not customizable
 - Offer the option to turn them off wholesale
 - Create an "elasticache-alerts" package a little like the endpoint services.  You offer a bunch of named alerts and use a mapping to populate dynamic values.  If you don't want to use the defaults, you call that module repeatedly, customizing all of the inputs like threshold, period, evaluation period, etc.

**Comment by michaelwittig** [comment]
I re-added the thresholds to the description. We try to keep things simple here. If we allow each and every alarm to be further parameterised we easily hit the max cloudformation parameter limit. If a user needs more control, don't pass an `ParentAlertStack` and define the alarms yourself.

Insipration: https://github.com/marbot-io/monitoring-jump-start

Im going to merge the PR soon (closing this).

**Comment by ambsw-technology** [comment]
Forgot that you can bulk-ignore using `ParentAlertStack`.

Yes we had to request an increased in CF Stacks.  They gave us 1800 immediately and authorized 10,000 after internal discussion, but (interestingly) told us "CFN no longer enforces stack limit if it is set higher than 1000".
