### ISSUE TITLE
IAM::Role Permission Boundary

### ISSUE THREAD

**Issue by ambsw-technology** [widdix/aws-cf-templates#464]
TemplateID: `*/*`
Region: `us-east-1`

Our client's security policy requires that every Role they create be subject to a [permission boundary](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_boundaries.html).  I'm hoping you'll accept a PR passing a `PermissionBoundary` into any module that creates an IAM Role (FWIW both here and `cfn-modules`).

Unfortunately, they were reminded of this requirement while deploying their production environment so I need to get make it available ASAP somewhere.  I can certainly maintain a fork while you consider the proposal, but wanted to get the ball rolling in an effort to minimize/avoid changing dependencies in our build pipeline.

**Comment by michaelwittig** [comment]
None of our IAM roles should grant iam access that would make it possible to create/modify policies or attach them? I don#t see how permission boundaries help here? What's the reason behind this requirement?

**Comment by claytondaley** [comment]
I've never used a permission boundary before so I'm not terribly qualified to speculate, but I assume it's this:

[How can I use permissions boundaries to limit the scope of IAM users and roles and prevent privilege escalation?](https://aws.amazon.com/premiumsupport/knowledge-center/iam-permission-boundaries/)

I know the role *does not* grant the policy, but I assume they cascade the requirement to ensure no role is created which could logically do so.

**Comment by claytondaley** [comment]
I received confirmation that the permission boundary must be attached to every Role that gets created.

**Comment by michaelwittig** [comment]
Work is in progress: see #465

**Comment by michaelwittig** [comment]
merged
