### ISSUE TITLE
Private Fargate Service with NAT Gatway getting Timeout

### ISSUE THREAD

**Issue by knuspertante** [widdix/aws-cf-templates#499]
Hey guys, hope you are good?

since I am quite new to the AWS environment and would like to run one of my docker containers via AWS ECS / Fargate for testing purposes and would like to automate this process, I came across your CloudFormation template for VPC & Fargate.

First of all, thank you very much for the good work!

I tried to use the templates to create a VPC in two zones (A & B) as well as a public and a private subnet. 
The service (docker container) should run in the private subnet and communicate with the outside world via NAT gateway. 

I executed the following templates with the following parameters in this order. 

1. https://console.aws.amazon.com/cloudformation/home#/stacks/create/review?templateURL=https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/vpc/vpc-2azs.yaml&stackName=vpc
2. https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/quickcreate?templateURL=https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/vpc/vpc-nat-gateway.yaml&stackName=nat-gateway&param_ParentVPCStack=vpc --> Parameter SubnetZone=A
3. https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/quickcreate?templateURL=https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/vpc/vpc-nat-gateway.yaml&stackName=nat-gateway&param_ParentVPCStack=vpc --> Parameter SubnetZone=B
4. https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/quickcreate?templateURL=https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/fargate/cluster.yaml&stackName=fargate-cluster&param_ParentVPCStack=vpc
5. https://eu-central-1.console.aws.amazon.com/cloudformation/home?region=eu-central-1#/stacks/quickcreate?templateURL=https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/fargate/service-dedicated-alb.yaml&stackName=fargate-service&param_ParentVPCStack=vpc&param_ParentClusterStack=fargate-cluster --> Parameter SubnetsReach=Private

However, I get a timeout for every request on one of the EIPs. I can reach the DNS of the load balancer via a Get-Request, but my service is not addressed and it returned default (the default html response I think).

**Comment by michaelwittig** [comment]
Not sure if I get the architecture right. The two EIPs are allocated to the NAT Gateways. You can not connect to them from the Internet. NAT is about accessing the Internet from the VPC, not the other way around.

If you want to communicate with your Fargate service, send your requests to the load balancer.

What exactly is the output if you run a command like this: `curl -vvv http://DOMAIN_NAME_OF_ALB/`?

**Comment by knuspertante** [comment]
@michaelwittig thx, really nice, that was the mistake. 

The template generated two load balancer I tested the false one before ;-) 

One has a Listener for Protocol: HTTP and Port: 80 with Rule: return fixed response 404
The other one as a Listener for Protocol: HTTP and Port: 80 with Rule: forwarding to EC2 Target. 

Is the first one necessary?

**Comment by michaelwittig** [comment]
The cluster's ALB is used on combination with the `service-cluster-alb.yaml` template. The idea here is to have many Fargate services sharing the same load balancer. You can use a host and/or PathPattern to route request to the correct Fargate service.

The `service-dedicated-alb.yaml` template (which you use) creates a dedicated ALB only for this single service.

**Comment by knuspertante** [comment]
Ah ok i get it!

Nice! Thx for this amazing work!
