### ISSUE TITLE
SSH Bastion security improvements

### ISSUE THREAD

**Issue by sandrokeil** [widdix/aws-cf-templates#52]
What do you think about the following SSH Bastion security improvements?

1. choose a SSH Port (is there a problem with other templates?)
1. enable SSH Port Knocking
1. deny IP for 3h if >= 3 wrong login attempts

**Comment by michaelwittig** [comment]
Hi @sandrokeil 
we aim for simple templates. Many things could be added but this would also increase the complexity. So I would argue that those features are not covered by "simple".
But feel free to make modifications to your installation. The templates are licensed under Apache 2 which should give you all the freedom to modify them and use them for commercial projects.
Thanks
Michael

**Comment by sandrokeil** [comment]
Alright, just wanted to know if I can bring a PR.
