### ISSUE TITLE
EC2 Private 

### ISSUE THREAD

**Issue by atzimot** [widdix/aws-cf-templates#522]
TemplateID: https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates-releases-eu-west-1/stable/ec2/al2-mutable-private.yaml
Region: `us-west-2`

(describe your issue here)

I can't create a Amazon Linux 2 (mutable, private).

I have the following parameters ParentVPCStack, ParentSSHBastionStack, ParentClientStack1

I get the following error:

   VirtualMachine    CREATE_FAILED    Failed to receive 1 resource signal(s) within the specified duration    AWS::EC2::Instance   

and after this event I have this event

    ROLLBACK_IN_PROGRESS    The following resource(s) failed to create: [VirtualMachine]. Rollback requested by user.

![image](https://user-images.githubusercontent.com/4029868/104889966-958da380-5977-11eb-8135-ffdf20fd0918.png)

**Comment by andreaswittig** [comment]
Which VPC template are you using? What's the value of the `SubnetName` parameter?

**Comment by atzimot** [comment]
I'm using the two zones VPC and SubnetName is SubnetAPrivate

**Comment by atzimot** [comment]
I have the same issue if I want to create the ECS cluster (cost optimzed)

**Comment by andreaswittig** [comment]
Did you add NAT Gateways to your private subnets?

**Comment by atzimot** [comment]
Yes I have installed a VPC: highly available SSH bastion host/instance, a cloudonaut.io template

**Comment by michaelwittig** [comment]
@atzimot you need nat gateways in private subnets as @andreaswittig pointed out. Not talking about a bastion host hete

**Comment by atzimot** [comment]
thanks this was the issue. I created the NAT and now is working
