### ISSUE TITLE
Questions about costs

### ISSUE THREAD

**Issue by dbeja** [widdix/aws-cf-templates#54]
Thank you for your template!

I read both posts about Wordpress on AWS and on the first approach you mentioned it could cost approximately 75$/month.
How do the costs of the second approach compare with the first approach?

Thanks!

**Comment by andreaswittig** [comment]
The most costly part of the infrastructure in both setups is EC2, ELB, and RDS. Costs should be more or less the same.

Have a look at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-paying.html to calculate the costs for your setup.
