### ISSUE TITLE
Wordpress Features Request

### ISSUE THREAD

**Issue by mhmdio** [widdix/aws-cf-templates#547]
Features Request

---

TemplateID:  `wordpress/wordpress-ha`
Region: `us-east-1`

- optional - Caching (redis preferred) with its wp plugin
- optional - ElasticSearch with its wp plugin

**Comment by michaelwittig** [comment]
Hi @mhmdio 
We have a template for [ElastiCache Redis](https://templates.cloudonaut.io/en/stable/state/#elasticache-redis) and [Elasticsearch](https://templates.cloudonaut.io/en/stable/state/#elasticsearch). I believe you should be able to install the mentioned plugin. Can you try that?

**Comment by michaelwittig** [comment]
no feedback received
