### ISSUE TITLE
ECS AutoScalingGroup - CREATE_FAILED

### ISSUE THREAD

**Issue by ghost** [widdix/aws-cf-templates#554]
TemplateID:  aws-cf-templates/ecs/cluster.yaml
Region: us-east-1

Hello,
I tried to create a stack using the aws-cf-templates/ecs/cluster.yaml template, but CloudFormation reports a CREATE_FAILED error:
```
test-ecs            ROLLBACK_IN_PROGRESS   The following resource(s) failed to create: [AutoScalingGroup]. Rollback requested by user.
AutoScalingGroup    CREATE_FAILED       Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
AutoScalingGroup    UPDATE_IN_PROGRESS  Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
AutoScalingGroup    CREATE_IN_PROGRESS  Resource creation Initiated
AutoScalingGroup    CREATE_IN_PROGRESS  -
```

**Parameters:**
```
ContainerExcessThreshold	10	-
ContainerMaxCPU	128	-
ContainerMaxMemory	128	-
ContainerShortageThreshold	2	-
DrainingTimeoutInSeconds	600	-
IAMUserSSHAccess	false	-
InstanceType	t3.small	-
KeyName	el-quijote	-
LoadBalancerCertificateArn	-	-
LoadBalancerIdleTimeout	60	-
LoadBalancerScheme	internet-facing	-
LogsRetentionInDays	14	-
ManagedPolicyArns	-	-
MaxSize	4	-
MinSize	2	-
ParentAlertStack	-	-
ParentAuthProxyStack	-	-
ParentS3StackAccessLog	-	-
ParentSSHBastionStack	-	-
ParentVPCStack	vpc-2azs	-
ParentWAFStack	-	-
PermissionsBoundary	-	-
StopContainerTimeoutInSeconds	30	-
SubnetsReach	Private	-
SystemsManagerAccess	true	-
```

For the VPC stack I used a template aws-cf-templates/vpc/vpc-2azs.yaml.

**Comment by michaelwittig** [comment]
Hi! Since you launch this in private subnets you need to deploy a mat gateway into both availability zones. See https://templates.cloudonaut.io/en/stable/vpc/#nat-gateway

> Am 19.05.2021 um 20:13 schrieb el-quijote ***@***.***>:
> 
> Hello,
> I tried to create a stack using the aws-cf-templates/ecs/cluster.yaml template, but CloudFormation reports a CREATE_FAILED error:
> 
> test-ecs            ROLLBACK_IN_PROGRESS   The following resource(s) failed to create: [AutoScalingGroup]. Rollback requested by user.
> AutoScalingGroup    CREATE
