### ISSUE TITLE
Wordpress template: Aurora support

### ISSUE THREAD

**Issue by pvangool** [widdix/aws-cf-templates#56]
Hi,

This is a feature request, and not a bug ;-).

I would be nice if the Wordpress template had support for multiple databases. Or simply different templates I guess. I would like to use it with Aurora instead of MySQL.

Thanks a lot for sharing these templates!

Thanks.

Paul

**Comment by andreaswittig** [comment]
Thanks for your feature request. Started implementing an additional template for Wordpress with Aurora.

**Comment by ILLUMINICE** [comment]
Hi Andreas,

Just extending my thanks here as well for working on this new template. Having all the advantages of your original WordPress CloudFormation template with Amazon Aurora is going to be a winning combination!

~ Michael

**Comment by pvangool** [comment]
Thanks! Really appreciate this.
