### ISSUE TITLE
Jenkins2-ha deployment failing: Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by Bloodr0ses** [widdix/aws-cf-templates#565]
```
AutoScalingGroup    CREATE_FAILED       Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
AutoScalingGroup    UPDATE_IN_PROGRESS  Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
AutoScalingGroup    CREATE_IN_PROGRESS  Resource creation Initiated
AutoScalingGroup    CREATE_IN_PROGRESS  -

```
Deployment failed in USE1 and USE2. 
vpc-2azs.yml was deployed first in both cases and the stack name was passed to the jenkins template as a parameter.
Please advise whether or not there is a simple fix or workaround for this. I've noticed the same error on a few older issue threads here but the solution doesn't seem to be the same.

**Comment by michaelwittig** [comment]
Hi, what"s the version of the template you are using? You can find the version in the stack outputs.

**Comment by Bloodr0ses** [comment]
Hi Michael, 

Sorry for taking so long to reply. I noticed you fixed this dependancy issue shortly after I reported it and the script now completes without error however I've noticed that it doesn't seem to create an instance of the ProvisionedThroughput Lambda function. Is that normal?

Thanks.

**Comment by michaelwittig** [comment]
I see.

The Lambda function is only deployed if you set the `EFSProvisionedThroughputInMibps` parameter to a value > 0.

I will close this issue since the initial bug is fixed.

**Comment by Bloodr0ses** [comment]
Perfect, thank you.
