### ISSUE TITLE
jenkins agents fail to start due to missing nodejs requirement

### ISSUE THREAD

**Issue by timharsch** [widdix/aws-cf-templates#586]
I'm still trying to dig further into this, but in the last couple of hours our agents stopped running jobs and looking into the log at /var/log/cloud-init-output.log shows:
```shell
 60  mock2                    available    [ =stable ]
 61  dnsmasq2.85              available    [ =stable ]
* Extra topic has reached end of support.
+ /opt/aws/bin/cfn-init -v --stack Jenkins --resource AgentLC --region us-east-2
Error occurred during build: Yum does not have nodejs available for installation
+ /opt/aws/bin/cfn-signal -e 1 --stack Jenkins --resource AgentASG --region us-east-2
ValidationError: Stack arn:aws:cloudformation:us-east-2:815262906617:stack/Jenkins/7daca480-efca-11ea-be61-0aa874bc8df2 is in UPDATE_COMPLETE state and cannot be signaled
```

I looked through the template and don't see a direct reference to nodejs, so I suspect some other yum library released an update that adds the requirement.

---

TemplateID: v12.11.0
Region: us-east-2

(describe your issue here)

**Comment by timharsch** [comment]
Looks like this is a problem unique to my modified template as I added steps to the template to load nodejs for use in our  test stacks.  I'll leave this issue open for a bit, as I determine the root cause (which may or may not be unique to my template).

**Comment by michaelwittig** [comment]
Hi @timharsch . There is no node.js in our templates by default .

**Comment by timharsch** [comment]
The root cause of the problem was this:
https://scotthelme.co.uk/lets-encrypt-old-root-expiration/

I can confirm that the AMI's in the latest jenkins template has up to date cacerts, so it should not be a problem in the latest.
