### ISSUE TITLE
CloudTrail LogsStream Details

### ISSUE THREAD

**Issue by imoisharma** [widdix/aws-cf-templates#587]
Hi there,

I deployed this https://github.com/widdix/aws-cf-templates/blob/master/security/cloudtrail.yaml stack with s3 data event true. I just notice, it's created multiple log stream under the cloudwatch log group and it's logging un-neccesaary events.

I am only interested in collecting and watching logs of one particular bucket. Can anyone help me on this?

**Comment by andreaswittig** [comment]
Hi @imoisharma,

thanks for writing in.

a) It is common and not an issue that a CloudWatch log group consists of multiple log streams. What bothers you about that?
b) As documented our template enables data events for all S3 buckets belonging to the account. We haven't implemented a whitelist as we thought this is more of a special case. You need to extend the template, if you want to specify a whitelist instead.

**Comment by imoisharma** [comment]
Hi @andreaswittig,

Thanks for the response. But when I deployed manually the cloud trail data event. I only received S3 logs. Any idea why is that ?

**Comment by andreaswittig** [comment]
Sorry, we are not providing AWS support here.
