### ISSUE TITLE
Error when uploading json file....

### ISSUE THREAD

**Issue by chrisparksaz** [widdix/aws-cf-templates#6]
Received this error message when attempting to upload "VPC with private and public subnets in two Availability Zones" template to AWS...

<img width="539" alt="screenshot" src="https://cloud.githubusercontent.com/assets/17152797/12939138/6baaff14-cf79-11e5-8e9d-aa418d8dffa2.PNG">

**Comment by andreaswittig** [comment]
Unfortunately I'm not able to reproduce your issue.

Are you uploading ``vpc/vpc-2azs.json``?

**Comment by chrisparksaz** [comment]
I'm probably just in over my head :) But, yes: I'm trying to upload vpc/vpc-2azs.json. 50 second clip shows what I'm doing per instructions:

[https://www.youtube.com/watch?v=ZsNLe-fSGtE](url)

**Comment by andreaswittig** [comment]
Thanks for the video. You are downloading a HTML file instead of a JSON file.

Use the following link to download the raw file instead: https://raw.githubusercontent.com/widdix/aws-cf-templates/master/vpc/vpc-2azs.json

Or checkout the whole repository.
