### ISSUE TITLE
OriginReadTimeout

### ISSUE THREAD

**Issue by zachnietling** [widdix/aws-cf-templates#61]
Hello,

Using a fresh install of the wordpress-ha template under the vpc-4azs parent stack, I occasionally have problems with plugins and other media taking long enough to upload that they timeout in the default 30 seconds set by CloudFront's OriginReadTimeout property. 

The plugin still installs, but the front end shows the timeout error, thus confusing the various non-technical individuals I work with who handle WP implementation. I tried manually changing the OriginReadTimeout from 30 to 60 (the maximum CF says it allows) in the CloudFront manager UI, but this then causes CF to blanket the whole site with a "ERROR The request could not be satisfied. CloudFront wasn't able to connect to the origin." response.

So, I made several test stacks while changing the CNAME for the subdomain to the loadbalancer instead of CF (in a panic), as changing the setting back to the default 30 seconds did not cause the CF error to go away. I was able to reproduce the error in fresh test stacks, just by running the template and changing only that one parameter, the whole site blew up and was irreversible. 

I referenced this:
http://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html

And tried modifying the wordpress-ha.yaml file to use OriginReadTimeout: 60 under CustomOriginConfig. CloudFormation returns "Encountered unsupported property OriginReadTimeout" when I try to do this. 

I can obviously instruct my coworkers to just ignore the upload timeout error, and have everyone swear not to touch the CF settings, but I was wondering if perhaps you might have some insight anyway. At this point I'll have to build a new stack for production and restore from backups because of the error, which isn't horrible... but if I could avoid it, that would be awesome too. 

Thanks so much, love the stack!

**Comment by michaelwittig** [comment]
Hi @zachnietling 

Will a 60 second timeout help you? If 30 is not enough? Or is the source of the problem something else?

If you make changes to AWS resources that are managed by CloudFormation you can run into serious issues when you update the stack the next time.

It looks like CloudFormation does not (yet) support to configure the origin read timeout. This feature is petty new ( https://aws.amazon.com/de/about-aws/whats-new/2017/03/announcing-configure-read-timeout-and-keep-alive-timeout-values-for-your-amazon-cloudfront-custom-origins/ ) so it will take some time until it is accessible in CloudFormation.

Thanks
Michael

**Comment by zachnietling** [comment]
60 or even 45 would be great. And yeah, running into those serious problems you spoke of :)

And that link is good to know, thanks for linking it!

**Comment by michaelwittig** [comment]
Okay. So I suggest that we wait until the CloudFormation team added that new feature as well. Usually this takes a few weeks.

**Comment by zachnietling** [comment]
Sounds like a plan. Thanks!
