### ISSUE TITLE
Plugin / Theme Upload Errors on Wordpress

### ISSUE THREAD

**Issue by jplatorre** [widdix/aws-cf-templates#62]
Hi guys, first off thanks for creating these templates. Liking them a lot.

I am encountering an issue on the Wordpress CF template that is preventing me from using WP all-in-one migration and also from manually installing themes and plugins.

When I attempt to upload/install a plugin via WP-Admin UI by navigating to Plugins > Add New > Upload Plugin I am greeted by the error "Are you sure you want to do this? Please try again." Not all that helpful of an error message. The same thing happens with themes. The theme and plugin are never uploaded.

The theme and plugin in question are both from OptimizePress.

I would prefer to use WP all-in-one migration since I am moving from an old site but it freezes/times out on Importing Database and the site crashes.

Any help is much appreciated as I am really stuck at the moment.

![image](https://cloud.githubusercontent.com/assets/4310042/25098979/610837d0-235f-11e7-91af-c65d3c06f14b.png)

**Comment by kbcaleb** [comment]
I think you are hitting a PHP limit because of the size of your theme probably. If you use the same template but with these changes it should be fine.
```shell
sed -i 's/memory_limit = 128M/memory_limit = 64M/g' /etc/php-7.0.ini
sed -i 's/post_max_size = 8M/post_max_size = 64M/g' /etc/php-7.0.ini
sed -i 's/max_execution_time = 30/max_execution_time = 600/g' /etc/php-7.0.ini
```

**Comment by michaelwittig** [comment]
The issue is related to the CDN CloudFront we are using.

**Comment by michaelwittig** [comment]
As a workaround, you could connect to the Load Balancer directly and bypassing the CDN.

**Comment by michaelwittig** [comment]
@jplatorre any news on this?

**Comment by jplatorre** [comment]
@michaelwittig Thanks for the follow up. I was able to get it resolved by changing the php upload settings and making a few other config modifications.

**Comment by michaelwittig** [comment]
@jplatorre changing the settings to something that @kbcaleb proposed? I would be interested in adding your changes to the template if they improved the situation for you.

**Comment by gurumark** [comment]
@jplatorre @kbcaleb 
What did you do apply these changes? I modified the template with the proposed sed commands and updated the stack from the cloudformation console. Nothing happed. Should I be logging in to the web servers to do this?
