### ISSUE TITLE
How to use Fargate Spot instances?

### ISSUE THREAD

**Issue by prolic** [widdix/aws-cf-templates#627]
When using the fargate cluster template located [here](https://github.com/widdix/aws-cf-templates/blob/master/fargate/cluster.yaml), how I can specify I want to use fargate spot instances?

**Comment by michaelwittig** [comment]
Hi @prolic You can specify to run your workload on spot in the service, e.g. https://github.com/widdix/aws-cf-templates/blob/master/fargate/service-cluster-alb.yaml#L324

**Comment by prolic** [comment]
Thank you!
