### ISSUE TITLE
HA NAT Gateway/Instance

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-cf-templates#65]
We only have one routing table that is shared by all subnets. I f we want to have HA NAt Gateway/Instance we need a route table per subnet so that we can add one NAT instance/Gateway per subnet as well.

**Comment by michaelwittig** [comment]
This will add breaking changes to the VPC stacks. Moved to version 4.x

**Comment by mvanbaak** [comment]
I know this ticket is closed etc, but I have a small question.
Why did you also create seperate route tables for the public subnets? 

As far as I can see, you only need seperate route tables for the private subnets. That way you can route private subnetA to nat gatewayA and private subnetB to nat gatewayB.
But the nat gateways/nat instances in the public subnets, can simply route their traffic to the default route of one single public route table.
(At least that's how we are doing it, and this works great. We even have multiple private subnets, sharing a single route table per availability zone)

Any ideas about pro/con for your option and our option?

**Comment by michaelwittig** [comment]
it was not necessary to split the public route table as well. but it's more flexible and has no disadvantages as far as I know=

**Comment by mvanbaak** [comment]
Thanks for the confirmation. Makes sense in your template set. Keep up the good work.
