### ISSUE TITLE
jenkins2-ha CF fails at MasterASG creation

### ISSUE THREAD

**Issue by sashasklar** [widdix/aws-cf-templates#73]
When running the latest version of jenkins2-ha.yaml, the CF creation is failing at the MasterASG step:

"Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement"

Here's the details:

1. Resources are being created in Oregon West. I have another instance of VPC+Jenkins2-ha created in US East.
2. Successfully created VPC using vpc2-az.yaml. Default parameters except for name.
3. Parameters for jenkins formation are default except for following:
    - Formation name
    - Reference to VPC (using VPC name)
    - Jenkins password

**Comment by michaelwittig** [comment]
Hi @sashasklar ,

can you deploy the Jenkins stack again and disable rollback. This gives you the ability to see what's going wrong.

You can do this by using the CloudFormation console, selecting Show Advanced Options, and then setting "Rollback on failure" to "No". 

Or if you use the CLI `--disable-rollback`

You then can inspect CloudWatch logs to see what's going on.

Sometimes the site that hosts the Jenkins rpm is not available and therefore the deployment fails. Unfortunately, cfn-init does not support any kind of fallback logic for downloading files.

**Comment by sashasklar** [comment]
Hi Michael,

Thanks for replying, sorry for the delay on my end.

I got the CloudFormation to run successfully but I wanted to pass along my findings in case they are useful in the future:

- When the MasterASG step failed, it would fail immediately. The time between the "Resource creation initated" and "Recieved Failure" Status was only a few seconds.
- The log group was created but there didn't seem to be anything in it.

I hope this is helpful, I'll disable rollback to try to capture more information if I encounter future failures.
