### ISSUE TITLE
Unclear how to chage master password for jenkins2-ha-agents

### ISSUE THREAD

**Issue by Ten0** [widdix/aws-cf-templates#743]
The template specifies that the password must not be changed:
https://github.com/widdix/aws-cf-templates/blob/f8d787f6b475d519867372d9b2625143a858ab9f/jenkins/jenkins2-ha-agents.yaml#L132

I need to change it, but I must assume this means that jenkins would break if I did change it.
Why doesn't it work?
Does this only run on first setup?
https://github.com/widdix/aws-cf-templates/blob/f8d787f6b475d519867372d9b2625143a858ab9f/jenkins/jenkins2-ha-agents.yaml#L1359-L1361

What needs to be done to change the password without it breaking?
Could this be documented in the template?

Thanks

**Comment by michaelwittig** [comment]
From checking the templates I would suggest you change the admin user password using the Jenkins UI. After that, you update the CloudFormation stack with the new password. 

I highly recommend to test the approach with a separate jenkins installation.
You better create a backup before doing so.
This is just working in theory. I never tried it.

**Comment by Ten0** [comment]
I'm guessing if I don't pre-change the password worse case scenario I revert to the old password and it works again?
Do you have any insight as to whether the `m_set_admin_password` script I mentioned above is theoritically supposed to run at every boot or only when provisioning the stack?

**Comment by michaelwittig** [comment]
> I'm guessing if I don't pre-change the password worse case scenario I revert to the old password and it works again?
Yes.

`m_set_admin_password` runs only once because the file /var/lib/jenkins/setup_done.txt is created at the end of the first run of the setup sequence and prevents further runs.

**Comment by Ten0** [comment]
Aah but yeah even that query reads from `/var/lib/jenkins/secrets/initialAdminPassword` so that won't work.
I see. Alright then yeah I guess changing the password first on Jenkins then in the template probably works.

**Comment by michaelwittig** [comment]
Let us know how it goes :)

**Comment by Ten0** [comment]
Manually changing the password then updating the template didn't get the master to restart automatically because it only updated the cfn-init resource, so I had to restart it manually by triggering an "instance refresh".
Other than that it worked fine. :)
