### ISSUE TITLE
VPC Endpoint for DynamoDB

### ISSUE THREAD

**Issue by michaelwittig** [widdix/aws-cf-templates#75]
Template available in branch https://github.com/widdix/aws-cf-templates/blob/vpc-endpoint-dynamodb/vpc/vpc-endpoint-dynamodb.yaml
Waits for general availability of DynamoDB endpoints

**Comment by mvanbaak** [comment]
https://aws.amazon.com/about-aws/whats-new/2017/08/vpc-endpoints-for-amazon-dynamodb-now-generally-available/?sc_channel=sm&sc_campaign=Launch&sc_publisher=TWITTER&sc_country=Global&sc_geo=GLOBAL&sc_outcome=awareness&trk=_TWITTER&sc_content=DynamoDB_c6aa945f_VPC_Endpoints&sc_category=Amazon_DynamoDB&linkId=41053481

hurray!

**Comment by aindenko** [comment]
cool 👍
