### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by oempire** [widdix/aws-cf-templates#79]
Ive completed the install as per the steps on
http://templates.cloudonaut.io/en/stable/wordpress/

However once it runs it doesn't complete instead I get the following in the log

Stack name:
wordpress-ha
Stack ID:
arn:aws:cloudformation:us-west-2:303563467503:stack/wordpress-ha/024ce810-4a
da-11e7-89a9-503ac9841a99
Status:
ROLLBACK_COMPLETE
03:03:20 UTC+1000 ROLLBACK_COMPLETE AWS::CloudFormation::Stack
wordpress-ha
03:03:09 UTC+1000 ROLLBACK_IN_PROGRESS
AWS::CloudFormation::Stack wordpress-ha No export named
-SubnetBPublic found. Rollback requested by user.
03:03:06 UTC+1000 CREATE_IN_PROGRESS AWS::CloudFormation::Stack
wordpress-ha User Initiated

So seems to be failing I don't get any ec2 instances made or anything,

Thanks

**Comment by michaelwittig** [comment]
have you missed step 1 ?

**Comment by oempire** [comment]
Hi, no step one, launch stack completed with CREATE_COMPLETE

however when i open it it shows several CREATE_IN_PROGRESS
'

2017-06-07	Status	Type	Logical ID	Status reason
02:36:41 UTC+1000	CREATE_COMPLETE	AWS::CloudFormation::Stack	vpc-2azs	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	
02:36:36 UTC+1000	CREATE_COMPLETE	AWS::EC2::Route	RouteTablePublicBInternetRoute	
02:36:35 UTC+1000	CREATE_COMPLETE	AWS::EC2::Route	RouteTablePublicInternetRoute	
02:36:35 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	
02:36:35 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	
02:36:35 UTC+1000	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	
02:36:21 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	Resource creation Initiated
02:36:21 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	Resource creation Initiated
02:36:20 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	
02:36:20 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	
Physical ID:vpc-2-Netwo-1T00U6GJEQ6HE
02:36:20 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	
02:36:20 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicInternetRoute	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	Resource creation Initiated
02:36:20 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicBInternetRoute	Resource creation Initiated
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	Resource creation Initiated
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicInternetRoute	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicBInternetRoute	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	
02:36:19 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	
02:36:18 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	
02:36:17 UTC+1000	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetBPrivate	
02:36:16 UTC+1000	CREATE_COMPLETE	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
02:36:16 UTC+1000	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetAPublic	
02:36:16 UTC+1000	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetBPublic	
02:36:16 UTC+1000	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetAPrivate	
02:36:05 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	Resource creation Initiated
02:36:05 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	Resource creation Initiated
02:36:05 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	Resource creation Initiated
02:36:04 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	Resource creation Initiated
02:36:04 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	
02:36:04 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	
02:36:03 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	
02:36:03 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	
02:36:02 UTC+1000	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTableBPublic	
02:36:01 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAcl	NetworkAclPrivate	
02:36:01 UTC+1000	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTableBPrivate	
02:36:01 UTC+1000	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTablePrivate	
02:36:01 UTC+1000	CREATE_COMPLETE	AWS::EC2::NetworkAcl	NetworkAclPublic	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	Resource creation Initiated
02:36:00 UTC+1000	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTablePublic	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPrivate	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPublic	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPrivate	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPrivate	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPublic	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPublic	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPrivate	Resource creation Initiated
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPrivate	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPrivate	
02:36:00 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPublic	Resource creation Initiated
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePublic	Resource creation Initiated
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPublic	Resource creation Initiated
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPrivate	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePrivate	Resource creation Initiated
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPrivate	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePublic	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPublic	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPublic	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPublic	
02:35:59 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePrivate	
02:35:57 UTC+1000	CREATE_COMPLETE	AWS::EC2::InternetGateway	InternetGateway	
02:35:57 UTC+1000	CREATE_COMPLETE	AWS::EC2::VPC	VPC	
02:35:40 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	InternetGateway	Resource creation Initiated
02:35:40 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	Resource creation Initiated
02:35:40 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	InternetGateway	
02:35:39 UTC+1000	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	
02:35:35 UTC+1000	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	vpc-2azs	User Initiated

**Comment by michaelwittig** [comment]
I guess you entered the wrong value into the ParentVPCStack parameter of the wordpress stack. It should be vpc-2azs not wordpress-ha

**Comment by oempire** [comment]
Hi,
Ive made sure on the WP /Aurora stack ive entered  ParentVPCStack vpc-2azs

Still rollback on WP Stack - 	No export named vpc-2azs-SubnetCPublic found. Rollback requested by user.

**Comment by michaelwittig** [comment]
wordpress is not in the stable docs.
you need a vpc with 3 subnets for aurora (vpc-3azs).
I'm closing this now since it is documented
