### ISSUE TITLE
Unable to Access WordPress Instances from Bastion Host

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#80]
Hi Andreas,

I'm having great difficulty reaching any of the WordPress instances from the Bastion Host. As you know I am using the new WordPress Aurora template.

I currently have both the default ec2-user access setup as well as private IAM based access (as you recommend). I'm able to login successfully via SSH to the Bastion Host using either the ec2-user or my IAM key. The problem occurs when I attempt to jump to the WordPress instances.

I'm using the correct commands and am making sure that forwarding of the authentication agent is enabled (I've enabled this in Putty, and also with the command itself).

I'm using this command to jump to the other instances: ssh -A user@private-ip-address

Whether I login to the Bastion Host as the ec2-user, or using my IAM user, I get the same error each time when jumping to the other instance:

**"Permission denied (publickey)."**

I'd greatly appreciate any help you can offer in troubleshooting this!

All my best,

~ Michael

**Comment by andreaswittig** [comment]
Thanks for using Github to ask for help!

I tried to reproduce your issue. Accessing the SSH bastion host and the Wordpress instances works fine for me.

Could you please provide the following information so that I'm able to help?

* All parameters of your SSH bastion host and Wordpress CloudFormation stacks.
* The verbose log messages when connecting via SSH to the bastion host as well as when connecting to the Wordpress instance. Use ssh -vvv ec2-user@<IP_ADDRESS> or find a way to enable verbose mode within your SSH client.

**Comment by ILLUMINICE** [comment]
Hi Andreas,

I had a feeling that asking for help in GitHub may be a little more convenient for you than email. I apologize for adding to your email load!

I just sent you screenshots of all the parameters in our Wordpress-Aurora and Bastion Host templates, in addition to a text file of my SSH session (in Putty) using verbose mode. I did send this via email to keep it all private.

I also responded to your direct email regarding accessing the EFS via SCP. It certainly sounds like the solution I've been looking for.

Thank you again for helping me!

~ Michael

**Comment by andreaswittig** [comment]
@ILLUMINICE Have you enabled agent forwarding in your Putty configuration when connecting to the bastion host? Did you load your private key with Putty pageant?

**Comment by ILLUMINICE** [comment]
Hi Andreas,

You were correct about the problem being caused by the agent forwarding. Apparently Putty wasn’t using the key I had entered into the saved session when jumping to the next server. I actually wasn’t using Pageant at the time, and had only entered the key once into the session settings. You would think Putty would be smart enough to use the same key when jumping servers, but apparently not.

The solution here was using Pageant. I entered both of my private keys into it (for the ec2-user and also my IAM key). I was just able to login successfully for the first time to one of the WordPress instances using my IAM key. So it was a very simple thing causing my problems. ;)

….

Now that I am in one of the WordPress instances I need to locate the EFS, and devise a way to easily transfer files to it (using SCP like you proposed). I don’t see the EFS mounted to the root of the instance, or anywhere in the instance at all. Is it mounted? Or is the webserver just grabbing the files to cache without any mount being needed?

Whatever the case, all I need now is SCP access to the EFS. If you can point me in the right direction I can probably figure out how to set that up…

~ Michael

**Comment by ILLUMINICE** [comment]
I just wanted to add that I located the actual WordPress files at /var/www/html, but I assume these are only the cached files on this one instance, and not the actual files in the EFS, right?

**Comment by ILLUMINICE** [comment]
As I'm reading the EFS mounting directions in the AWS documentation, it seems to say this would be the mount location if the EFS is mounted automatically. So perhaps this is it?

**Comment by ILLUMINICE** [comment]
Hi Andreas,

I have some good news, and only need you to confirm one thing for me...

**Is the EFS mounted to WordPress instances at /var/www/html ?**

I need to confirm that these are the actual EFS files, and not the cache that you setup using OPcache. This way if I make changes to files in this location it is permanent, and will propagate to all other WP instances.

....

The good news is that I was able to successfully setup an SSH Tunnel to one of the WordPress instances through the Bastion Host, by using WinSCP. I usually use FileZilla, but it doesn't have direct integration for SSH Tunnels (you need to use it in conjunction with Putty for that). I chose to use WinSCP because it makes setting up tunnels extremely easy. It also fully support FTP, sFTP, and SCP. After a few minutes of using WinSCP I was extremely impressed by it. It seems to be more powerful than FileZilla, and has some great integration features with Putty and Pageant.

Btw, according to my reading SCP is only for file transfers, and not for directory listing and deleting files. For this reason I'm using sFTP at the moment in WinSCP, since it supports both formats.

Assuming this is the EFS I'm now tunneling to, this means I'm all ready to go and can finally start setting up our site. Thank you again for all your earlier help and pointers!

All my best,

~ Michael

**Comment by andreaswittig** [comment]
@ILLUMINICE Yes, EFS is mounted at `/var/www/html`. You are able to make changes to these files. It will take up to 300 seconds until the new versions are delivered due to OPCache.

**Comment by ILLUMINICE** [comment]
Hi Andreas,

Thanks for confirming the EFS mount location. I figured that was it!

I just ran a little test trying to make some changes to files there (using WinSCP via sFTP) and ran into an immediate problem. Whenever I try to either delete a file or overwrite a file I receive the following error message:

**Permission denied.
Error code: 3
Error message from server: Permission denied**

I noticed that all the files are owned by Apache, and perhaps this is the source of the problem? Assuming I am right, do you know how to work around this?

Btw, I'm using sFTP instead of SCP, because SCP can only transfer files and not delete them apparently.

....

Few other quick questions if you can spare a moment...

1. Can OPcache be tweaked (like the 300 seconds for example) outside of the CloudFormation template? Or is this something that can only be controlled through the template?

2. Is the CDN (CloudFront) caching all files within WordPress, or only certain files/directories? (like /wp-content for example)

3. I took a look at wp-config.php and noticed several things I would have setup differently had I been installing WordPress. The database name, username, and password are all "wordpress" which is something I would have never done (this can't be good for security, though within AWS I'm not sure). I also would usually be customizing the table prefix so it's not the default "wp_". Considering the template sets this all up ahead of time, is it now impossible to change these values? (these would have made good parameters within the CF template if possible)

4. In the past I used to use caching plugins like "WP Rocket" to help cut down on load times. But here in AWS with your template we're using a combination of OPcache and a CDN. So the question is, do I even need a plugin based caching solution anymore? (or perhaps it wouldn't be fully compatible)

5. When I first installed the various CF templates I noticed in the advanced section of the last step that there were notification options from which you could select an existing Amazon SNS topic. Was it necessary to select the topic created by your Alerts template there? It looked to me like your template worked independently from this function.

Thanks again Andreas!

~ Michael

**Comment by michaelwittig** [comment]
this seems to be off topic
