### ISSUE TITLE
	Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

### ISSUE THREAD

**Issue by subeasec** [widdix/aws-cf-templates#81]
I am getting the following failure when using your stock templates (vpc-2azs.yaml and wordpress-ha.yaml).

I was able to run the vpc-2azs.yaml with no issues.  When running the wordpress-ha.yaml I got the following errors:

	12:02:31 UTC-0400	CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	AutoScalingGroup	Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

Here is my parameters list:
![image](https://user-images.githubusercontent.com/20689719/27254584-e8a6eadc-5358-11e7-8580-82839fd45701.png)

**Comment by andreaswittig** [comment]
I assume you have created your stack in `us-east-1`. Are there any logs containing errors showing up at [https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logs:]?

**Comment by subeasec** [comment]
Yes I am creating these in us-east-1.

No logs showing in cloudwatch.

I have attached the events logs.

If you just use the stock scripts does it work for you?

[events.txt](https://github.com/widdix/aws-cf-templates/files/1089981/events.txt)

**Comment by andreaswittig** [comment]
Could you please share the console output from one of the Wordpress instances?

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-console.html

**Comment by subeasec** [comment]
So I turned off Rollback and it looks like 2 instances were created, but only after another instance failed.  I have attached all three logs.  I am still getting the "Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement".


[server3_failed.txt](https://github.com/widdix/aws-cf-templates/files/1091773/server3_failed.txt)
[server2.txt](https://github.com/widdix/aws-cf-templates/files/1091772/server2.txt)
[server1.txt](https://github.com/widdix/aws-cf-templates/files/1091771/server1.txt)

**Comment by subeasec** [comment]
So it looks like every time an instance was taken out of service in response to a ELB system health check failure.

![ec2 management console 2017-06-21 10-46-21](https://user-images.githubusercontent.com/20689719/27390394-1cf8e0d8-566f-11e7-9d7e-e53eabf13add.png)

**Comment by subeasec** [comment]
I set the "MinSize: 1" for the AutoScalingGroup and things installed correctly -- an instance still failed, but at least it completed the install.
![ec2 management console 2017-06-21 11-36-56](https://user-images.githubusercontent.com/20689719/27392956-ff09c5f4-5675-11e7-8f97-b02fb43a65df.png)

**Comment by michaelwittig** [comment]
Your server3 failed to run the task 02_wordpress which runs the /root/wordpress.sh script

The problem is, that CloudWatch Logs is not yet configured when  02_wordpress fails. That's why you can not find anything in CloudWatch Logs and so we can not really debug the cause of the ise. I opened an issue #84 to address the CW Logs issue.

**Comment by michaelwittig** [comment]
v4.3.0 now contains the updated templates where CF Logs is installed first. This will help us to debug your issue. Can you update to that template version? http://templates.cloudonaut.io/en/v4.3.0/wordpress/

**Comment by subeasec** [comment]
It installed with no issues or failures without any changes to the script.

 

The only issue now is that I can’t access the wordpress site.  When I go to tradehoudsddev.com it says:

tradehoundsdev.com’s server DNS address could not be found.

 

Jay

**Comment by andreaswittig** [comment]
Have you created a A/Alias record for tradehoundsdev.com pointing to the CloudFront distribution?

**Comment by subeasec** [comment]
That worked.  May want to add that step to your instructions.

 

Thanks.

 

Jay

**Comment by michaelwittig** [comment]
It's already in the docs:

Step 13: Create or update a CNAME/Alias record for your custom domain name pointing to the CloudFrontDomainName from the previous step.
