### ISSUE TITLE
Static website - RedirectDomainName ExistingCertificate and  not optional

### ISSUE THREAD

**Issue by jrbenito** [widdix/aws-cf-templates#86]
Hi,

First of all thanks for providing these templates.

At [template line 23](https://github.com/widdix/aws-cf-templates/blob/master/static-website/static-website.yaml#L23) seems that RedirectDomainName is optional. However, when running AWS command line we get:

`An error occurred (ValidationError) when calling the CreateStack operation: Parameters: [RedirectDomainName, ExistingCertificate] must have values`

Also, I am providing `CertificateType=CreateAcmCertificate` and I think this shall make `ExistingCertificate` not necessary.

I could run it by passing `RedirectDomainName=''` and `ExistingCertificate=''`. 

Is this expected behavior?

**Comment by michaelwittig** [comment]
thanks for reporting. I submitted a fix to the master branch. This fix will be included in the next release which is not yet planed.
