### ISSUE TITLE
Fn::ImportValue

### ISSUE THREAD

**Issue by GeorgeLopes** [widdix/aws-cf-templates#87]
My subnets has this names:

Private Subnet - C / Private Subnet - D and Public Subnet - A / Public Subnet - B

Made changes on code to support then

Fn::ImportValue': !Sub '${ParentVPCStack}-Private Subnet - C'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-Private Subnet - D'
      - - 'Fn::ImportValue': !Sub '${ParentVPCStack}-Public Subnet - A'
        - 'Fn::ImportValue': !Sub '${ParentVPCStack}-Public Subnet - B'

When execute stack occurs this error

No export named -Private Subnet - C found. Rollback requested by user.
--

**Comment by michaelwittig** [comment]
Hi @GeorgeLopes 
All our templates are designed to work together. If you want to use an existing VPC that you have not created with one of our vpc templates, you can use a legacy wrapper template ( e.g. https://github.com/widdix/aws-cf-templates/blob/master/vpc/vpc-2azs-legacy.yaml ) to wrap your existing template into the format you need for all the other templates.
