### ISSUE TITLE
IAM Users longer than 32 characters cause import_users.sh to fail

### ISSUE THREAD

**Issue by GeorgeLopes** [widdix/aws-cf-templates#88]
Creating an environment with all templates:

In Bastion template this error occurs

CREATE_FAILED | AWS::AutoScaling::AutoScalingGroup

The following resource(s) failed to create: [AutoScalingGroup]. . Rollback requested by user.
--

AutoScalingGroup | bastion-AutoScalingGroup-P2HZ46452O2U | AWS::AutoScaling::AutoScalingGroup | DELETE_IN_PROGRESS
-- | -- | -- | --

Thanks

**Comment by michaelwittig** [comment]
Hi @GeorgeLopes 
can you create the stack again, this time disable **Rollback on failure** in the Options step (expand Advanced).
And then we have to check the logs in CloudWatch Logs to find the root cause.

**Comment by GeorgeLopes** [comment]
@michaelwittig hi, only this error that i can find

2017-07-14 01:44:13,071 P2569 [INFO] Command c_import_users
2017-07-14 01:44:14,373 P2569 [INFO] -----------------------Command Output-----------------------
2017-07-14 01:44:14,374 P2569 [INFO]    useradd: invalid user name 'CloudWatchSlackIntegrationIIIIIIII'
2017-07-14 01:44:14,374 P2569 [INFO] ------------------------------------------------------------
2017-07-14 01:44:14,374 P2569 [ERROR] Exited with error code 1

**Comment by GeorgeLopes** [comment]
@michaelwittig don´t enable Synchronize public keys of IAM users to enable personalized SSH access and template works

**Comment by michaelwittig** [comment]
the error log you posted is very helpful. Can you post the full name of the IAM user CloudWatchSlackIntegration. It seems that the username is longer than 32 characters, can you conform this?

**Comment by GeorgeLopes** [comment]
@michaelwittig yes, 34 chars.

**Comment by michaelwittig** [comment]
I will add a check that skips users with length > 32.

**Comment by mvanbaak** [comment]
Shouldn't we create a bug in the aws-ec2-ssh as well?
