### ISSUE TITLE
Custom Request to Use S3 Bucket for Uploads Folder (Static Content) in Combination with EFS for All Other Files

### ISSUE THREAD

**Issue by ILLUMINICE** [widdix/aws-cf-templates#94]
Hi Michael,

I have a custom request very similar to that of Issue #43.

I'm also more than willing to hire you to edit our template for this purpose (for a fair price).

Basically what I need to accomplish is to store the WordPress uploads folder (/wp-content/uploads/) in an S3 bucket, while still using the EFS to store everything else. We would still want to use CloudFront, in conjunction with both the EFS and the S3 bucket.

Your response in #43 about static content most likely being served by the CDN is a good point, but it doesn't help us with the pricing differences between the EFS and S3. Storage costs in the EFS are much more expensive than S3, and this is going to quickly become a problem for our platform as it grows.

I agree that executable code is far better served from the EFS, and this is something I like a lot in your templates. But static content that is uploaded by users can take up a lot of space, and there's no benefit to storing that in the EFS. It's critical that we store our uploads folder content in S3, as otherwise the costs will become prohibitive.

As I am new to CloudFormation, I don't feel comfortable editing the template myself. We're using the WordPress Aurora template currently. Would you be willing to make the necessary changes for a fee?

We can discuss the terms privately over email...

All my best!

~ Michael

**Comment by ILLUMINICE** [comment]
Hi Michael,

Any word on this request? We can connect directly via email to talk about it.

Frankly, I think this would be a wise improvement for the entire template, and not just for my use-case.

~ Michael

**Comment by michaelwittig** [comment]
You could try this on your own: install this plugin: https://de.wordpress.org/plugins/amazon-s3-and-cloudfront/

it depends on: https://de.wordpress.org/plugins/amazon-web-services/

since this is all stored on EFS you don't need to touch the template at all.

**Comment by ILLUMINICE** [comment]
Hi Michael,

I've just taken a good look at this plugin, including the PRO version. I'm actually familiar with the author (Delicious Brains), as I've been using his "WP Migrate DB Pro" plugin for a few years now. This is a quality author.

While the plugin looks well-designed, I'm concerned about taking this kind of plugin-based approach for the following reasons...

**1.** They actually charge for this plugin based on the number of Media Library items. This turned me off immediately, as we're building a major platform that will have hundreds of thousands of items in the future, perhaps more. I don't like the idea of having any kind of limits based on number of media uploads.

**2.** From the plugin documentation, it says that the plugin doesn't upload files directly to S3. Instead it uploads the files first to the default server, then copies them to S3. It does have an option to delete the original file when the upload is completed. But this approach isn't good for a number of reasons. It puts unnecessary traffic and stress on the web servers, and, there's the possibility of original files not being deleted. It's just unnecessary overhead, when the files should be copied directly to S3.

**3.** I'm not sure if this plugin will work with the existing CloudFront distribution. It says it supports CloudFront, but I'm unclear how it would work exactly. CloudFront is currently set to use the LoadBalancer as it's origin. If the media files were suddenly in an S3 bucket, would CloudFront know this and still be able to cache the files?

**4.** This is probably the most important objection... My understanding of using CloudFormation is that all resources and configurations should be generated from the templates. To use this plugin we would need to create a separate S3 bucket manually. Doesn't this go against the idea of having the templates control everything? I watched Andreas' course on CloudFormation, and it was very specific about not mixing manual setups with CF stacks.

**5.** In my experience if you can do things without another WP plugin, it's better. Using this plugin really makes us dependent upon it. Our entire website is based on publishing media. Using this plugin would make us terribly dependent upon it. I'd much rather side-step this plugin and have this done with the CF templates and our stack directly if possible.

.....

That's everything I can think of right now. I highly value your opinion on this. If you think we can do this all within CloudFormation, I'd much rather go that route for the reasons stated above. At this moment I'm not sure what is best... I would gladly pay you to do this job in CF if it's the better way.

All my best,

~ Michael

**Comment by michaelwittig** [comment]
the only way to achieve this is to modify WordPress with a plugin

**Comment by ILLUMINICE** [comment]
I understand... and will reply back separately via email (as Andreas emailed me about this too)...
