### ISSUE TITLE
New Relic Monitoring Broken

### ISSUE THREAD

**Issue by elricsfate** [widdix/aws-cf-templates#95]
Newrelic monitoring does not appear to work out of the box. 

Uncertain for the reason but APM will not work with the default setup.

**Comment by michaelwittig** [comment]
Hi @elricsfate 
There is a log file under /var/log/newrelic/nrsysmond.log
anything useful in there?

**Comment by elricsfate** [comment]
Howdy @michaelwittig 

From what I can tell, nrsysmond does not handle php/application level monitoring and is instead for their server/infrastructure monitoring. It also appears nrsysmond it will be deprecated soon.

https://docs.newrelic.com/docs/servers/new-relic-servers-linux/installation-configuration/linux-configuration-new-relic-servers 

https://discuss.newrelic.com/t/important-upcoming-changes-for-new-relic-servers-and-legacy-alerting-features/49474

I'm still working out how to get that done with their install script by passing in debconf parameters but haven't quite got it working. I believe it would also be possible to simply handle it with standard Cloudfront stuff but there is a load of symlinking and other stuff that is handled that would need to be added (which would be optimal to avoid if their script already covers it)

Docs for running the install in silent mode. 

https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/silent-mode-install-script-advanced

I'm pretty sure the reason I'm having issues is due to how I'm passing in environment variables (I'm still learning CF)

Let me know if I can provide more details.

**Comment by michaelwittig** [comment]
Yes, we only install the New Relic Servers agent which comes with a "free tier". It looks like New Relic Infrastructure no longer comes with a "free tier" so I'm not sure if we should continue to support New Relic in the templates. Because we don't support Datadog and others.

But back to your original question: You want to enable the application level monitoring by New Relic?

**Comment by elricsfate** [comment]
@michaelwittig 

This was a source of confusion for myself as well. 

APM has a free tier but it's not made very apparent on their website.

If the lack of free tier was holding back implementation, might make sense to add it as it's a useful feature for performance troubleshooting..

See the two links below:

[Forum Link](https://discuss.newrelic.com/t/is-there-still-free-apm-lite-plan/43076/3)
[Documentation Link](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/apm-data-retention)

And that is correct, would like to add APM monitoring.

**Comment by michaelwittig** [comment]
okay. so to sum this up:

* The templates use the New Relic Servers agent, APM is not installed which is not properly documented
* New Relic Servers goes away and is replaced by New Relic Infrastructure
* New Relic APM is a feature that you would like to use

If this is correct, I suggest that we create two tickets out of this:
1.) Migrate to New Relic Infrastructure
2.) Add NewRelic APM

Does this makes sense?

**Comment by elricsfate** [comment]
@michaelwittig 

Apologies, it seems that I missed this and did not reply. 

Is there still a wish to integrate NR Infra if it does not have a free tier?

**Comment by elricsfate** [comment]
Issues created @michaelwittig
